runtime: python312
entrypoint: gunicorn -b :$PORT request_handler:app

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: .*
  script: auto
