# -*- coding: utf-8 -*-
"""Large list of metres, input by Dr. Dhaval Patel.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

dhaval_vrtta_data_small = [
    ('śrī', 'G'),
    ('strī', 'G G'),
    ('nārī', 'G G G'),
    ('mṛgī', 'G L G'),
    ('kanyā', 'G G G G'),
    ('paṅkti', 'G L L G G'),
    ('tanumadhyā', 'G G L L G G'),
    ('śaśivadanā', 'L L L L G G'),
    ('vasumatī', 'G G L L L G'),
    ('madhumatī', 'L L L L L L G'),
    ('madalekhā', 'G G G L L G G'),
    ('kumāralalitā', 'L G L L L G G'),
    ('haṁsamālā', 'L L G G L G G'),
    ('vidyunmālā', 'G G G G — G G G G'),
    ('chitrapadā', 'G L L G L L G G'),
    ('māṇavaka', 'G L L G G L L G'),
    ('haṁsaruta', 'G G G L L L G G'),
    ('samānikā', 'G L G L G L G L'),
    ('pramāṇikā', 'L G L G L G L G'),
    ('campakamālā', 'G L L G G G L L G G'),
    ('nārācaka', 'G G L G L G L G'),
    ('halamukhī', 'G L G L L L L L G'),
    ('bhujagaśiśubhṛtā', 'L L L L L L G — G G'),
    ('śuddhavirāṭ', 'G G G L L G L G L G'),
    ('paṇava', 'G G G L L — L L G G G'),
    ('mayūrasāriṇī', 'G L G L G L G L G G'),
    ('rukmavatī', 'G L L G G G L L G G'),
    ('mattā', 'G G G G — L L L L G G'),
    ('manoramā', 'L L L G L G L G L G'),
    ('upasthitā', 'G G — L L G L L G L G'),
    ('indravajrā', 'G G L G G L L G L G G'),
    ('upendravajrā', 'L G L G G L L G L G G'),
    ('sāndrapada', 'G L L G G L L L L G G'),
    ('sumukhī', 'L L L L G — L L G L L G'),
    ('dodhaka', 'G L L G L L G L L G G'),
    ('śālinī', 'G G G G — G L G G L G G'),
    ('vātormī', 'G G G G — L L G G L G G'),
    ('bhramaravilasita', 'G G G G — L L L L L L G'),
    ('śrī', 'G L L G G — L L L L G G'),
    ('rathoddhatā', 'G L G L L L G L G L G'),
    ('svāgatā', 'G L G L L L G L L G G'),
    ('vṛntā', 'L L L L — L L L L G G G'),
    ('bhadrikā', 'L L L L L L G L G L G'),
    ('śyenikā', 'G L G L G L G L G L G'),
    ('upasthita', 'L G L L L G G G L G G'),
    ('śikhaṇḍita', 'L G L L L G G G L G G'),
    ('mauktikamālā', 'G L L G L L G G L L G'),
    ('candravartma', 'G L G L L L G L L L L G'),
    ('vaṁśastha', 'L G L G G L L G L G L G'),
    ('indravaṁśā', 'G G L G G L L G L G L G'),
    ('toṭaka', 'L L G L L G L L G L L G'),
    ('drutavilambita', 'L L L G L L G L L G L G'),
    ('puṭa', 'L L L L L L G G G L G G'),
    ('pramuditavadanā', 'L L L L L L G L G G L G'),
    ('mauktidadāma', 'L G L L G L L G L L G L'),
    ('kusumavicitrā', 'L L L L G G — L L L L G G'),
    ('jaloddhatagati', 'L G L L L G L G L L L G'),
    ('bhujaṅgaprayāta', 'L G G L G G L G G L G G'),
    ('sragviṇī', 'G L G G L G G L G G L G'),
    ('priyaṁvadā', 'L L L G L L L G L G L G'),
    ('maṇimālā', 'G G L L G G G G L L G G'),
    ('lalitā', 'G G L G L L L G L G L G'),
    ('pramitākṣarā', 'L L G L G L L L G L L G'),
    ('ujjvalā', 'L L L L L L G L L G L G'),
    ('vaiśvadevī', 'G G G G G — G L G G L G G'),
    ('jaladharamālā', 'G G G G — L L L L G G G G'),
    ('navamālinī', 'L L L L — G L G L L L G G'),
    ('prabhā', 'L L L L L L G L G G L G'),
    ('mālatī', 'L L L L G L L G L G L G'),
    ('pañcacāmara', 'L G L G L G L G L G L G'),
    ('tāmarasa', 'L L L L G L L G L L G G'),
    ('kṣamā', 'L L L L L L G G L G G L G'),
    ('praharṣiṇī', 'G G G L L L L G L G L G G'),
    ('rucirā', 'L G L G L L L L G L G L G'),
    ('mattamayūra', 'G G G G — G L L G G L L G G'),
    ('mañjubhāṣiṇī', 'L L G L G L L L G L G L G'),
    ('nandinī', 'L L G L G L L L G L L G G'),
    ('candrikā', 'L L L L — L L G G L G L G G'),
    ('asambādhā', 'G G G G G — L L L L L L G G G'),
    ('aparājitā', 'L L L L L L G — L G L L G L G'),
    ('praharaṇakalikā', 'L L L L L L G — L L L L L L G'),
    ('vasantatilakā', 'G G L G L L L G L L G L G G'),
    ('induvadanā', 'G L L L G L L L G L L L G G'),
    ('alolā', 'G G G L L G G — G G G L L G G'),
    ('śaśikalā', 'L L L L L L L — L L L L L L L G'),
    ('mālā', 'L L L L L L — L L L L L L L L G'),
    ('maṇiguṇanikara', 'L L L L L L L L — L L L L L L G'),
    ('malinī', 'L L L L L L G G — G L G G L G G'),
    ('prabhadraka', 'L L L L G L G L L L G L G L G'),
    ('elā', 'L L G L G — L L L L L L L L G G'),
    ('candralekhā', 'G G G G L G G — G G L G G L G G'),
    ('ṛṣabhagajavilasita', 'G L L G L G — L L L L L L L L L G'),
    ('vāṇinī', 'L L L L G L G L L L G L G L G G'),
    ('śikhariṇī', 'L G G G G G — L L L L L G G L L L G'),
    ('pṛthvī', 'L G L L L G L G — L L L G L G G L G'),
    ('vaṁśapatrapatita', 'G L L G L G L L L G L L — L L L L G'),
    ('hariṇī', 'L L L L L G — G G G G — L G L L G L G'),
    ('mandākrāntā', 'G G G G — L L L L L G — G L G G L G G'),
    ('narkuṭaka', 'L L L L G L G L L L G L L G L L G'),
    ('kokilaka', 'L L L L G L G — L L L G L L — G L L G'),
    ('kusumitalatāvellitā', 'G G G G G — L L L L L G — G L G G L G G'),
    ('meghavisphurjita', 'L G G G G G — L L L L L G — G L G G L G G'),
    ('śārdulavikrīḍita', 'G G G L L G L G L L L G — G G L G G L G'),
    ('suvadanā', 'G G G G L G G — L L L L L L G — G G L L L G'),
    ('vṛtta', 'G L G L G L G L G L G L G L G L G L G L'),
    ('sragdharā', 'G G G G L G G — L L L L L L G — G L G G L G G'),
    ('madraka', 'G L L G L G L L L G — L G L L L G L G L L L G'),
    ('aśvalalita', 'L L L L G L G L L L G — L G L L L G L G L L L G'),
    ('mattākrīḍa', 'G G G G G G G G — L L L L L — L L L L L L L L L G'),
    ('tanvī', 'G L L G G — L L L L L L G — G L L G L L L L L L G G'),
    ('krauñcapadā', 'G L L G G — G L L G G L L L — L L L L L L L —L L L L G'),
    ('bhujaṅgavijṛmbhita', 'G G G G G G G G — L L L L L L L L L L G —L G L L G L G'),
    ('apavāha', 'G G G L L L L L L — L L L L L L — L L L L L L — L L G G G'),
    ('caṇḍavṛṣṭiprayātadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G'),
    ('arṇadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('arṇavadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('vyāladaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('jīmūtadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('līlākaradaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('uddāmadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('śaṅkhadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('samudradaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('bhujaṅgadaṇḍaka', 'L L L L L L G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('pracitakadaṇḍaka', 'L L L L L L L G G L G G L G G L G G L G G L G G L G G'),
    ('upacitrā', ['L L G L L G L L G L G', 'G L L G L L G L L G G']),
    ('drutamadhyā', ['G L L G L L G L L G G', 'L L L L G L L G L L G G']),
    ('vegavatī', ['L L G L L G L L G L L G G', 'G L L G L L G L L G G']),
    ('bhadravirāṭ', ['G G L L G L G L G G', 'G G G L L G L G L G']),
    ('ketumatī', ['L L G L G L L L G G', 'G L L G L G L L L G G']),
    ('ākhyānikī', ['G G L G G L L G L G G', 'L G L G G L L G L G G']),
    ('viparītākhyānikī', ['L G L G G L L G L G G', 'G G L G G L L G L G G']),
    ('hariṇaplutā', ['L L G L L G L L G L G', 'L L L G L L G L L G L G']),
    ('aparavaktra', ['L L L L L L G L G L G', 'L L L L G L L G L G L G']),
    ('puṣpitāgrā', ['L L L L L L G L G L G G', 'L L L L G L L G L G L G G']),
    ('yavātparāmatīya', ['G L G L G L G L G L G L', 'L G L G L G L G L G L G']),
    ('padacaturūrdhva', [' ........ ', ' ............ ', ' ................', ' ....................']),
    ('āpīḍa', [' L L L L L L G G ', ' L L L L L L L L L L G G ', ' L L L L L L L L L L L L L L G G ', ' L L L L L L L L L L L L L L L L L L G G ']),
    ('kalikā', [' L L L L L L L L L L G G ', ' L L L L L L G G ', ' L L L L L L L L L L L L L G G ', ' L L L L L L L L L L L L L L L L L L G G ']),
    ('lavalī', [' L L L L L L L L L L G G ', ' L L L L L L L L L L L L L L G G ', ' L L L L L L G G ', ' L L L L L L L L L L L L L L L L L L G G ']),
    ('amṛtadhārā', [' L L L L L L L L L L G G ', ' L L L L L L L L L L L L L L G G ', ' L L L L L L L L L L L L L L L L L L G G ', ' L L L L L L G G ']),
    ('udgatā', [' L L G L G L L L G L ', ' L L L L L G L G L G ', ' G L L L L L L G L L G ', ' L L G L G L L L G L G L G ']),
    ('saurabhaka', [' L L G L G L L L G L ', ' L L L L L G L G L G ', ' G L G L L L G L L G ', ' L L G L G L L L G L G L G ']),
    ('lalita', [' L L G L G L L L G L ', ' L L L L L G L G L G ', ' L L L L L L L L G L L G ', ' L L G L G L L L G L G L G ']),
    ('upasthitapracupita', [' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' L L L L L L L L G ', ' L L L L L L L L L L G L L G G ']),
    ('vardhamāna', [' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' L L L L L G L L L ', ' L L L L L L L L L L G L L G G ']),
    ('śuddhavirāḍārṣabha', [' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' G G L L G L G L G ', ' L L L L L L L L L L G L L G G ']),
    ]
