# -*- coding: utf-8 -*-
"""Large list of metres, input by Dr. Dhaval Patel.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

dhaval_vrtta_data = [
    ('anīcakam', 'L G L L L L L L L L L G'),
    ('līlā', 'L L L L G G L G L'),
    ('pratibhādarśanam', 'L L G G L L G G L L L L G G'),
    ('karṇapālikā', 'G L G L G G L G L G'),
    ('utkaṭapaṭṭikā', 'G G L L G L G L G L G L L L L L L G G L G G L G'),
    ('sindhurayā', 'G L L G G G'),
    ('vyāyogavatī', 'G G L L G L L L L L L G'),
    ('chidram', 'G G L L L'),
    ('parimalam', 'L L L L G G L L L L G L L G G'),
    ('virāṭ', 'G G G L L G L G L G'),
    ('vikuṇṭhakaṇṭhaḥ', 'G L G L G L G L G L G L G L G L G L G L G L G L G G'),
    ('vinandinī', 'L L G L L G L L G L L G L G'),
    ('rāmābaddham', 'G G G G L L L L G G L L G G L L L L G G L L G'),
    ('jaladharamālā', 'G G G G L L L L G G G G'),
    ('abhīkam', 'L G G L G G G'),
    ('dūrāvalokaḥ', 'G G G G L G G L L L L L L G G G L G G L G'),
    ('purohitā', 'L G L G L G G'),
    ('prothā', 'G G G L L L'),
    ('nakhapadā', 'L L L G L G G L'),
    ('pārāvārāntastham', 'G G G G G G G G G L L G G L L L L G G G L L G'),
    ('vaḍiśabhedinī', 'L L L G L L L G L G'),
    ('karmaṭhaḥ', 'G L L G L L G L L G L L G'),
    ('vigāhitageham', 'L L L L L L L L L L G G G G G L L L L G L L G G'),
    ('kamalaparam', 'L L L L G G L L L L G G G L L G'),
    ('sācīkṛtavadanā', ['L L L L G G G L L G G', 'G G L L L L G L L L L G']),
    ('vaṁśottaṁsā', 'G G L L G G L L G G G G G G'),
    ('karṇāṭakam', 'G G L G L L L G L G L L L G L G L L L L L L L L L G'),
    ('maru', 'L G L G L L L L'),
    ('ardharutam', ['G L L L L L L G G L L L L', 'G L L L L L L G L L G L L']),
    ('acalapaṅktiḥ', 'G L G L L L L L G G'),
    ('vṛndā', 'G G L G L G L'),
    ('lalitālabālam', 'L L G L G L L G G G G'),
    ('madhumallī', 'L L G G L L G L G'),
    ('pratīpavallī', 'L L G L L G G L L G L G L G G G'),
    ('nagamahitā', 'L L G G L L G L L L L G'),
    ('bhājanaśīlā', 'G G L L G G G L G G L G G'),
    ('prabhāvatī', 'G G L G L L L L G L G L G'),
    ('prabhāvatī', [' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ']),
    ('viṣāṇāśritam', 'L G G L L L G L G G L L L G L G G L L L G L G G L G'),
    ('ardhakusumitā', 'G L L L L G L L L L L L G'),
    ('bhāsitasaraṇiḥ', 'G L L L L L L L L L L G'),
    ('ammethī', 'G G G G L G L'),
    ('citrapadā', 'G L L G L L G G'),
    ('śālabhañjikā', ['L L G L L L G L G L G', 'G L L G G L G L G L G']),
    ('abhrabhramaśīlā', 'G G L L G G L L G G L L G'),
    ('haraṇi', 'L L L'),
    ('prapātāvatāram', 'L G G L G G G L G L G'),
    ('lolatanu', 'L L G G L L L'),
    ('aṭṭāsinī', 'G G L G L L G L G L L G L'),
    ('darpamālā', 'L G G L G G G L G G L G G'),
    ('navasarā', 'G G G L L L G'),
    ('bhūriśikhā', 'L L G L L G G G G G G L L G'),
    ('dhavalakarī', 'L L L L L L G L L G G G'),
    ('atijani', 'G G G G L L L L'),
    ('śaralīḍhā', 'L L L L G L L G G'),
    ('mārdaṅgī', ['L L G L L L L L G L L L G G', 'G G G L L L L G L L L L L L L L G G']),
    ('proñchitā', 'L L G G L G L'),
    ('kāhī', 'L L G G G L L'),
    ('dvimilā', 'L L G L L G L L G L L G L L G L L G L L G L L G'),
    ('aparaprīṇitā', ['L L L L L L L L G G G L G G L G', 'L L L L L L G G L G G L G']),
    ('ḍhuṇḍhi', 'L L G G G L'),
    ('pramāthinī', ['L L L L G L L G L G L G G', 'L L G G L L G L G L G G']),
    ('taralanayanam', 'L L L L L L L L L L L L'),
    ('bhramarāvalikā', 'L L G L L G L L G L L G L L G'),
    ('mayūrī', 'L G G G L G L'),
    ('utpalamālikā', 'G L L G L G L L L G L L G L L G L G L G'),
    ('madhupāli', 'L L G L L G L L G L L G L L'),
    ('vipulapālikā', 'G L G L G L L L L G L G'),
    ('ardhakalā', 'L L G L L G L L G'),
    ('modakam', 'G L L G L L G L L G L L'),
    ('prasṛmaramarālikā', 'L L L L L G L G L G L G'),
    ('viralā', 'L L G L L L L G L G L G'),
    ('bālavikrīḍitam', 'G L L L L G L G L L L G L G G L G'),
    ('anāsavavāsitā', ['L L G G L L G L G L G L L L G G', 'L L L G L L L G L G L G L G G']),
    ('ṛju', 'L G L L'),
    ('karālī', 'G G L G G L G G'),
    ('meduradantam', 'G L L G L L G L L G L L G L L G L L G L L G L L'),
    ('kālambī', 'G G G L G L L'),
    ('gotragarīyaḥ', 'G L L G G L L L L G G L L G G L L L L G L L G'),
    ('puṭaḥ', 'L L L L L L G G G L G G'),
    ('balorjitā', 'L L L L G L G L G L G G'),
    ('doṣā', 'G G L L G L L'),
    ('anāsādi', 'G L G L G G L'),
    ('kośi', 'G L L L L L L'),
    ('vārddhi', 'L G L G L'),
    ('tuṅgā', 'L L L L L L G G'),
    ('kalpalatāpatākinī', 'G G G L L L L L L L L G L L G L G L G'),
    ('campakamālā', 'G L L G G G L L G G'),
    ('kurarīrutā', 'L L L L G L G L L L G L L G'),
    ('śiśumukhī', ['L L L G L L L G L L G L G', 'L L L G L L L L G L G L G']),
    ('atimohā', 'L L G G L L G G'),
    ('gaganodgatā', 'G L G L L L G L G L L G L G'),
    ('ākatanu', 'L G L G G L L L'),
    ('pravāhikā', 'L G L G G L G G L G G L G'),
    ('arajaskā', 'L G L L G G'),
    ('unnālam', 'G G L L L L L L G G'),
    ('bahulābhram', 'L L G G L L L L G G L L G G G'),
    ('vikatthanam', 'L G L L G L L L G L L G'),
    ('karṇinī', ['G L G L L L G L L G G', 'G L G L L L G L G L G']),
    ('karṇinī', [' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ']),
    ('vaiśvadevī', 'G G G G G G L G G L G G'),
    ('śaṅkhadyuti', 'L L G G L L'),
    ('pramodapariṇītā', ['L L L L L L G L G L G L G G', 'L L L L G L L G L G L L L G G']),
    ('kuhī', 'L G L L L G'),
    ('niṣadham', 'G L L G L G L L G'),
    ('sopadhi', 'G L G G L L'),
    ('saṁpātaśīlā', ['G G L G G G G L G G', 'L L G L L L G G G L G G']),
    ('varīyaḥ', 'L G G L L'),
    ('kīralekhā', 'L L L G L G L L L G L G G'),
    ('prabhāsitā', ['G G G L L G L G L G', 'L L G L L G L G L G']),
    ('samit', 'L L L L G G L L L L G'),
    ('kīlālam', 'G L L G G G G G L L'),
    ('pravaralalitam', 'L G G G G G L L L L L G G L G G'),
    ('vīraṇamālā', 'G L L G G L L L L L L G'),
    ('anindagurvinduḥ', 'L L L L G G G G L G L G G G'),
    ('varivaśitā', 'L L G L L G L L L L L L G'),
    ('vinidrasindhuraḥ', 'G L G G L G G L G G L G L G L G L G L G L G L G L G'),
    ('lalitā', 'G G L G L L L G L G L G'),
    ('phulladāma', 'G G G G G L L L L L L G G L G G L G G'),
    ('aprītā', 'L L L G G G L L'),
    ('dhaureyam', 'G L L G L L L L G L L G L L L L L L L L G G G G'),
    ('mantrikā', 'G L G G G L'),
    ('kalpāhārī', 'L L L L L L L L L L L L G G G G'),
    ('bhujagahāriṇī', 'L L L G L G L L G L G'),
    ('śiprā', 'G G G G G G G'),
    ('hindīram', 'G G G G G L G'),
    ('śukavanitā', 'L L G L L G G L L G L L L L L L G'),
    ('māyāvinī', 'L L G G G L G'),
    ('mattakokilam', 'G L G L L G L G L L G L G L L G L G'),
    ('puṣpaśakaṭikā', 'G L L L L G G G L G G L G G'),
    ('kuberakaṭikā', 'L L G L L G L G L L L G G'),
    ('narāvaliḥ', 'G G L G L L L L L L L L G'),
    ('vaṁśapatrapatitam', 'G L L G L G L L L G L L L L L L G'),
    ('narī', 'L G G L G'),
    ('śarakāṇḍaprakāṇḍam', 'L L G G L G L L L G L G G L G G L G G L G'),
    ('nandathu', 'G L L L G G L'),
    ('karṇalatā', 'L L G G L L G L L L L G L L G'),
    ('kanakamañjarī', 'L L L G L G G L G L G'),
    ('ṛcā', 'L G L L G G L'),
    ('mattamayūraḥ', 'G G G G G L L G G L L G G'),
    ('guṇasārikā', 'L G L L G L L G L L G L G'),
    ('saurabhaśobhāsāraḥ', 'G L L G G G G G L L L L L L G L L L L G'),
    ('kaṭhinī', 'L L L L L G L G L G G L G'),
    ('ūhinī', 'G L G L L G L G G L G L L G L'),
    ('ūhinī', [' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ']),
    ('vātormī', 'G G G G L L G G L G G'),
    ('nīranidhiḥ', 'L L L G G L L L L L'),
    ('madhu', 'L L'),
    ('sundarī', ['L L G G L L G L G L G', 'L L G L L G L G L G']),
    ('samānikā', 'G L G L G L G L'),
    ('gṛhiṇī', 'L L G G G G L'),
    ('vandāruḥ', 'G G G L L G G L L'),
    ('ardhāntarālāpi', 'G G L G G L G G L G G L G G L G G L'),
    ('kamalākarā', ['G L L G L L G L L G G', 'G L L L L L L G L L G G']),
    ('bhujaṅgī', 'L G G L G G L G G L G'),
    ('bhastrānistaraṇam', 'G G G L L G G L L L L L L G L G L G L L G G'),
    ('indravimānam', 'G L L G G L L L L G G G G L L L L L L L L G G'),
    ('drutapadam', 'L L L G L L L G L L G G'),
    ('mandākrāntā', 'G G G G L L L L L G G L G G L G G'),
    ('cakitā', 'G L L L L G G G G G G L L L L G'),
    ('suvanamālikā', 'G G L L L G L G L L L G'),
    ('vajrālī', 'G G L L G G G G G G G G G G G'),
    ('kalanā', ['L L G L G L L L G L L G G', 'L L G L G L L L G L G L G']),
    ('bhāsamānabimbam', 'G L G L G L G L L L L G L G L G L L L L G L G G'),
    ('ayanapatākā', 'G G G L L L G G G'),
    ('haripadam', 'L L L L L L L G'),
    ('candravartma', 'G L G L L L G L L L L G'),
    ('bhasalamadam', 'G L L L L G L G L G G L G'),
    ('mihirā', 'L L L L L G L G G L G G'),
    ('hīralambi', 'G L L G L L G L G L'),
    ('pṛthvī', 'L G L L L G L G L L L G L G G L G'),
    ('dolā', 'L L G G'),
    ('vidalā', 'L L L L L G G G L G L L G'),
    ('mukulitakalikāvalī', 'G L G L L L L L L G L G'),
    ('atiprativinītā', ['L L G G L L G L G L L L G G', 'L L L L G G L G L G L G G']),
    ('lalitapatākā', 'L L L L L G L G G L G G G G'),
    ('tilakā', 'L L G L L G'),
    ('cūḍāpīḍam', 'G G G G L L L L L L G G G G'),
    ('drutamukham', 'L L L L L L L L L L L L G G G G L G L G G G'),
    ('kulacāri', 'L G L G L L G L'),
    ('varhāturā', 'G G L G L L G G L G'),
    ('sākṣī', 'L L G L L G L G L G G G'),
    ('manoramā', 'L L L G L G L G L G'),
    ('rodhakam', 'L L L G L L G L L G G'),
    ('hāṭakaśāli', 'G G L L G L'),
    ('dantālikā', 'G G L G G G G L G G G G L G G L'),
    ('mañjubhāṣiṇī', 'L L G L G L L L G L G L G'),
    ('jāhamukhī', 'G L L G L L G L L G L L G G'),
    ('nemadhāri', 'L G L G L L G L G L'),
    ('madanajavanikā', 'L L L L G G L L L L L L G'),
    ('niravadhigatiḥ', 'L L L L L G G L L L G'),
    ('kṛtakatikā', 'L L L L L L L L L L L G'),
    ('ṭaṅkaṇam', 'G L G L L L G L G L L L G L G L L L G'),
    ('dhūmrālī', 'L G G L G G G G G G'),
    ('maṇḍalam', 'G L L L G'),
    ('sainikam', 'L G L G L G L G L G L'),
    ('madanamālikā', 'L L L G L G L L L G L G G L G'),
    ('vidhuravirahitā', 'L L G G G L L G G G L L L L L L G'),
    ('upadārikā', 'G L G L G L L L G L G'),
    ('badhirā', 'L L G G L L G L G L G G'),
    ('hariluptā', ['L L G L L G L L G L G', 'L L G G L L G L L G L G']),
    ('viyadvāṇī', ['L L G G L L G L G L G G', 'G G G L L G L G L G G G']),
    ('aparavaktram', ['L L L L L L G L G L G', 'L L L L G L L G L G L G']),
    ('avahitrā', ['G L L G L L G L L G G', 'L L G L L G L L G L L']),
    ('gaganagatikā', 'G L G L L G L G L L L L L G'),
    ('amṛtagatiḥ', 'L L L L G L L L L G'),
    ('tantrī', 'G G G L G G'),
    ('kalahetikā', 'L L G L G L L G L G L L L G'),
    ('valabhī', 'G L L G L L G L G L G G'),
    ('ketumatī', ['L L G L G L L L G G', 'G L L G L G L L L G G']),
    ('kinnaṭakaḥ', ['G G L L G L L G L L G', 'L L G L L G L L G L L G']),
    ('makaramukhī', 'L L L L L L L L L G'),
    ('mukhalā', 'L L L L G G L L G'),
    ('atiśāyinī', 'L L G L L G L G L G L L L G L G G'),
    ('karamālā', 'L L G G L L G G L L G G'),
    ('mahodhikā', 'L G L G L L G'),
    ('bhrūḥ', 'L G G G L'),
    ('upadhāyyā', 'G L L L L L L L G G'),
    ('balākā', 'L G G'),
    ('vilambalalitam', 'L G L L L G L G L L L G L G L L L G L G L L G'),
    ('virudarutam', 'G G G G L L L L G G L L G G L L G'),
    ('vāsantī', 'G G G G G L L L L G G G G G'),
    ('viraloddhatā', 'G G G L L G L G L L L G'),
    ('jatu', 'L L G L L'),
    ('naṭakaḥ', ['L L G L L G L L G L L G', 'G G L L G L L G L L G']),
    ('śalabhalolā', 'L G G L G G L G L L L G G'),
    ('ṣaṭpaderitam', 'L L L G L G L L L G L G L L L G L G'),
    ('alakālikā', 'G G L G L L G L G L L G L G'),
    ('rūpāmālī', 'G G G G G G G G G'),
    ('vimāninī', ['G G G L L L L G L G L G', 'L L G G L L G L G L G']),
    ('pathikāntā', 'G L L L L L L G L L G G'),
    ('śramitaśikhaṇḍī', 'G L L L L G G L L G G'),
    ('pramodatilakā', 'G G L G L L L G L L G L G'),
    ('karīritā', ['L L G G L L L G L G L G', 'L L G L L G L G L G']),
    ('śāradacandraḥ', 'G G L L G G L L G G L L G G'),
    ('svarṇābharaṇam', 'L L G L L G L L G L L G L L L L G G G L L G'),
    ('somaśruti', 'L G G G L L'),
    ('kroḍakrīḍam', 'G G G G L L L L L L L L G L G G L G'),
    ('naraśikhī', 'L L L G L L L G L L L G L L L G'),
    ('nīlagirikā', 'G L L L G L L L G L L G'),
    ('amitanagānikā', 'G L L L L G L G L L G L G'),
    ('upacitrā', ['L L G L L G L L G L L', 'G L L G L L G L L G G']),
    ('bhārākrāntā', 'G G G G L L L L L G L G L L G L G'),
    ('kupyam', 'G L L L L G L G L G'),
    ('ahīnatālī', ['G G G L L L L G L G L G', 'L L G G L L L L G L G L G L G G']),
    ('vasanaviśālā', 'L L L L L L L G G G G G'),
    ('kalahaṁsaḥ', 'L L G L G L L L G L L G G'),
    ('pṛṣadvatī', 'G G L G L G G L G L G L G'),
    ('nirvādhikā', 'G G L G L L G'),
    ('anavīrā', 'L L G G L L L L G'),
    ('vipulāyitam', 'G G G L L L L G L G L L L L L L G L G L G L G'),
    ('ativāsitā', 'L L G L G G G L G L L G'),
    ('kṛtayuḥ', 'L L L L L L L L'),
    ('arditapādam', 'G L G L L L L G L L G G'),
    ('veśi', 'G L L L L L L L'),
    ('rañjakam', 'G L L L L G L L G'),
    ('tāvuri', 'G G L L'),
    ('digīśaḥ', 'L L G L G L G G'),
    ('vāṇinī', 'L L L L G L G L L L G L G L G G'),
    ('kiṇapā', 'G L L L G G G'),
    ('viśakalitā', 'G G G G L L L L G G L L L L G'),
    ('sukarṇapūram', 'L L L G L G L G L G L G G'),
    ('ānanamūlam', 'G L L G G L L G G L L G G'),
    ('alakā', 'L L L L L L L L L L L L L L L L L L L L L L L L G'),
    ('kurarikā', 'L L L G L G G G'),
    ('aśokānokaham', 'G G G G L L L L L G L L L L L G L G G G L G G L G G'),
    ('yamanakam', 'L L G L L L G'),
    ('īdṛṣam', 'G L G L G L G L G L G L G L G L G L G L'),
    ('īdṛṣam', [' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ']),
    ('udarkaracitā', 'L L G L L G L G L L L G'),
    ('alolā', 'G G G L L G G G G G L L G G'),
    ('parilekhaḥ', 'L G L L G L L G L L G G'),
    ('javanaśālinī', 'L L G L L G L G G L G'),
    ('vasantahāsaḥ', 'G G G G L L L L G L G G'),
    ('karmadā', 'G L G L L G'),
    ('sīdhuḥ', 'L L G G L L G L G L G'),
    ('cayanam', 'L G G L L L L L'),
    ('hariṇīplutā', ['L L L G L L G L L G L G', 'L L G L L G L L G L G']),
    ('gallakam', 'L L L L L L L G G L G'),
    ('viṣṭambhaḥ', 'L L G L L G L L G G G'),
    ('prabhadrakam', 'L L L L G L G L L L G L G L G'),
    ('śambūkaḥ', 'L L G G G G G'),
    ('vāriśālā', 'L G L G G L G G'),
    ('anu', 'L L L L G G L'),
    ('arbhakamālā', 'G L L G G L L L L G G L L L L G G G L L G G'),
    ('śallakaplutam', 'L L G G L G L G'),
    ('asurāḍhyā', ['G G G L L G L G L G G', 'L L L L L L G L G L G G']),
    ('rucivarṇā', 'L G L L L G L G L L L G G'),
    ('antarvanitā', 'G G G L L G G G G G G'),
    ('kalamatallikā', 'L L L G L G L L L G L G L L L G L G G L G'),
    ('hali', 'L L L L L'),
    ('bhujaṅgasaṅgatā', 'L L G L G L G L G'),
    ('vāridhiyānam', 'G L L G G L L G L'),
    ('praharaṇakalikā', 'L L L L L L G L L L L L L G'),
    ('vimukhī', ['L L L L L L G L L L L G G', 'L L L L L L L L G L L G G']),
    ('haṭhinī', 'G G G L G L L G'),
    ('maulisrak', 'G G G L L G L'),
    ('kalādharaḥ', 'G L G G L G L G L G L G L G'),
    ('vaṁśalaḥ', 'G L L G G L L G L L G L L G L L G'),
    ('pāṁśu', 'L L L G L'),
    ('sandhyā', 'G G L L L L G G'),
    ('sāmapadā', 'G G G L L G L L L L G'),
    ('amaracamarī', 'L L L L L L L L L L L L L L L L L L L L L L G'),
    ('halamukhī', 'G L G L L L L L G'),
    ('pāli', 'L L G G L'),
    ('saṁśrayaśrīḥ', 'G G L G G L G G L G L'),
    ('lalitam', 'L L L L L L G G G G L G'),
    ('paṅkajadhāriṇī', 'G G G L L G L G L L L G G'),
    ('padmāvarttaḥ', 'G G G G G G G G G G'),
    ('paridhārā', 'L L G G L G G G'),
    ('pramāṇikā', 'L G L G L G L G'),
    ('ulapā', 'G L L L L L G'),
    ('pārṣatasaraṇam', 'G L L L L L L G G G G G L L L L L L L L L L G G'),
    ('upavali', 'L L L L L L'),
    ('ākekaram', 'G G L L L L L L G'),
    ('viṭ', 'G L L G L'),
    ('jananidhivelā', 'L L L L G G L L G G G G L L G'),
    ('candrāpīḍam', 'G G G G G G G G G G G G G G G G'),
    ('adritanayā', 'L L L L G L G L L L G L G L L L G L G L L L G'),
    ('amarāvatī', ['L G L G L G L G L G L G G', 'G L G L G L G L G L G L']),
    ('kalāpadīpakam', 'G L G L G L G L G L G L G L G L G L G'),
    ('vīravimānam', 'G L L G L L G L L G L L G L L G L L G G'),
    ('viparītākhyānakī', ['L G L G G L L G L G G', 'G G L G G L L G L G G']),
    ('kṣaram', 'L G L L L L L L'),
    ('aruntudaḥ', ['L L G L L G L G L G', 'L L L L G L L G L G L G']),
    ('śaśikarī', 'L L G L L L G G L'),
    ('culakam', 'L L L L L L L L L'),
    ('kṛkapādi', 'L L L G L G L L G L'),
    ('kṣupam', 'L G L L L'),
    ('sammadamālikā', 'L L L L L G L L G L G'),
    ('padmāvatī', ['L L G L G L L L G L L G G', 'G G L G L L L G L L G G']),
    ('sari', 'L L L L L G'),
    ('nīrohā', 'L L G G L G G G G G'),
    ('valivadanam', 'L L L L G G G G G G L L L L G G'),
    ('valivadanam', [' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ']),
    ('garudavāritā', 'L G L L L G L G L L G L G'),
    ('drutamadhyā', ['G L L G L L G L L G G', 'L L L L G L L G L L G G']),
    ('jīmūtadhvānam', 'G G G G G G G G G G G G G G G G G G G G G G G G G G'),
    ('kaladhautapadam', 'L L G L L G L L G L L G L L G G'),
    ('ciraruciḥ', 'L G G L L L G'),
    ('satketuḥ', 'G G G L L L L L L L G L G L G L G G'),
    ('aniloddhatamukhī', 'L L L G L G G L G L L L G'),
    ('sitastavakaḥ', 'G G L G L L L G G L G L L L G G L G L L L G'),
    ('ṛtam', 'L L L L L L L L G L'),
    ('agarim', 'L L L L L L L L L L L'),
    ('nayamālinī', 'L L L L G L G L L L G G'),
    ('mālyopastham', 'L L L L L L L L L L G G G G G G'),
    ('asudhā', ['L L G G L L G L G L G', 'G G G L L G L G L G']),
    ('kalaham', 'L L G G L L G G G'),
    ('priyā', 'L L G L G'),
    ('pikālikā', 'G L L L G L L G L G L G'),
    ('dvāravahā', 'G L G G G L L G G G'),
    ('vidyā', 'G G L L G L L G'),
    ('līḍhālarkaḥ', 'G G G G G L L L G L G G'),
    ('viśvavirāṭ', 'G G G L L G L G L G G'),
    ('māṇḍavakam', 'L L L G G L L G'),
    ('karmiṣṭhā', 'G L L L L G G G G'),
    ('suvihitā', 'L G G L L G L G L L L G'),
    ('suvihitā', [' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' L L L L L L L L G L L L L L L L L G ', ' L L L L L L L L L L G L L G G ']),
    ('prākārabandhaḥ', 'G G L G G L G G L G G'),
    ('śīrśavirahitā', 'G G L L G G G L L G L L L L G'),
    ('ūpikam', 'L G G G G L G'),
    ('kaṅkaṇakvāṇaḥ', 'G L G G L G G L G G L G G L G G L G G L G G'),
    ('ānatā', 'G G G L L L G L G G L G G'),
    ('titikṣā', 'G L L L L L L G G L L L L L L G G'),
    ('titikṣā', [' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ']),
    ('kalali', 'L L L G G'),
    ('tumulakam', 'L L L L L L L L L L L L L L L L L L'),
    ('upacitaratikā', 'G L L L L L L G L L G L G'),
    ('vṛtumukhī', 'L L L G L L G G'),
    ('udaraśri', 'L L G L L G G G G'),
    ('sugandhiḥ', 'L L G L L L L G G'),
    ('taravārikā', 'L L L L L G L L G L G L L G L G'),
    ('mṛgī', 'G L G'),
    ('anaṅgapadam', ['G L L G L L G L L G L L G', 'L L G L L G L L G L L G G']),
    ('sāraṅgaḥ', 'G G L G G L G G L G G L'),
    ('sāraṅgaḥ', [' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ']),
    ('khelāḍhyam', 'G G G L L G G G G'),
    ('kṛtamaṇitā', 'G L L L L L L L L G'),
    ('harikāntā', 'L L G G L L G G L L G'),
    ('anilohā', 'L L G G L L G G L L G G L L G G'),
    ('hariṇīplutā', ['L L G L L G L L G L G', 'L L L G L L G L L G L G']),
    ('sārāvanadā', 'G G L L G L G G'),
    ('śarahatiḥ', 'L L L L L L L L L L L L L L L'),
    ('prabodhaphalitā', 'G L G L L L G L G L L L G'),
    ('vāsaki', 'L L L L G L L'),
    ('plavaṅgamaḥ', 'G L L G L L G G L G L L G L G'),
    ('narācaḥ', 'L G L G L G L G L G L G L G L G'),
    ('mālatī', 'L L L L G L L G L G L G'),
    ('kandaḥ', 'L G G L G G L G G L G G L'),
    ('puraṭi', 'L L L L G L G'),
    ('anṛtanarma', 'L L G G L L G L'),
    ('aśokalokaḥ', 'G G G G G G G G G G G G G G L G L G G G G'),
    ('mahimāvasāyi', 'L L G G L L G L G L'),
    ('akusumacaram', ['G L L L L L L G L L G G', 'G L L G L L G L L G G']),
    ('bhīmāvarttaḥ', 'G G G G L L L L L L L L L L G G'),
    ('karapallavodgatā', 'L G G L G G L L G L G L G'),
    ('pārāntacārī', 'L G G G G L G G'),
    ('cāru', 'G L'),
    ('karṇiśaraḥ', 'G L L G L L G L L G G L L G'),
    ('paripuṅkhitā', 'G L G L L G L G L G L G'),
    ('madhumatī', 'L L L L L L G'),
    ('citrā', 'G G G G G G G G G L G G L G G'),
    ('vipinatilakam', 'L L L L L G L L L G L G G L G'),
    ('jagatsamānikā', 'L L G L L G L G L G L G G'),
    ('induvaṁśā', 'G G L G G L L G L G L G'),
    ('kalpakāntā', 'G L G G G L G G L G G L G G'),
    ('nirmadhuvāri', ['G G L G L L G L G L L G L', 'L L G L G L L L G L G L G']),
    ('jarā', 'L G L L G L L G L G'),
    ('bhinnapadam', 'G L L G L L L G L G'),
    ('varṇabalākā', 'L L G L L G G L L G G'),
    ('sindhusauvīram', 'G L G G L G G L G G L G G L G G L G'),
    ('paravaktram', ['L L L L G L L G L G L G', 'L L L L L L G L G L G']),
    ('nāgāri', 'L L G L G G G L'),
    ('śiśirā', ['G G L G G L L G L G L G', 'L G L G G L L G L G L G']),
    ('saurabhavarddhinī', 'L L L L G G L L G L G'),
    ('maṅkuram', 'G G G L G L'),
    ('ketuḥ', ['G L L G L G L L L G G', 'L L G L G L L L G G']),
    ('prasṛmarakarā', 'L L L L L G L G G L G'),
    ('kaṭhodgatā', 'L L G L G L G'),
    ('ahari', 'L L L L L G L'),
    ('ujjhitakadanam', 'G L L L L L L G L L G L L G L L L L L L L L L L G G'),
    ('kuraṅgāvatāraḥ', 'L G G L G G L L G L L G'),
    ('niṣkalakaṇṭhī', 'G L L G G G L L G G G L L G G L L G G L L G'),
    ('prativinītā', ['L L L L G G L G L G L G G', 'L L G G L L G L G L L L G G']),
    ('krīḍacandram', 'L G G L G G L G G L G G L G G L G G'),
    ('avācīkṛtavadanā', ['G G L L L L G L L L L G', 'L L L L G G G L L G G']),
    ('arāli', 'L G L L G L L G'),
    ('kiṣku', 'G G L G G L G L'),
    ('kalavallivihaṅgaḥ', 'L G L G G L L G G L G G'),
    ('gopāvedī', 'L L L G G G G G'),
    ('kirmīram', 'G G G G L G G'),
    ('viśalyam', 'L G G L G G L G G'),
    ('śambaram', 'L L L G L L G L L G L G L L L G L L G L L G L G'),
    ('varaśaśi', 'G L G L L L L'),
    ('kalilā', 'L L G L L G L G'),
    ('avandhyopacāraḥ', 'L G G L G G L G G L G G L G G L G G L G'),
    ('kākalīkalakokilaḥ', 'G L G L L G L G L L G L G L L G L G L L G L G L L G'),
    ('paṅkāvaliḥ', 'G L L L L L L G G L L L L'),
    ('vaiyālī', ['L L L L L L G L G L G', 'G G G L L G L G L G']),
    ('ibhabhrāntā', 'G G G L G G G'),
    ('sragviṇī', 'G L G G L G G L G G L G'),
    ('drutavilambitam', 'L L L G L L G L L G L G'),
    ('mithunamālī', 'L L L L L L G G G G G G'),
    ('upakārikā', 'L L G L G L L G L G L L G L'),
    ('kusumitalatāvellitā', 'G G G G G L L L L L G G L G G L G G'),
    ('upasarasī', 'L L G L L L L G L L L L G'),
    ('vidyullekhā', 'G G G G G G'),
    ('cakram', 'G L L L L L L L L L L L L G'),
    ('ahiṁsā', 'G L G L G G G'),
    ('arkaśeṣā', 'G L G L G L G L G L G L G G'),
    ('narhi', 'L G G L G G L'),
    ('śaśivadanā', 'L L L L G G'),
    ('cārucāraṇam', 'G L G L L L L L G L'),
    ('pratardi', 'L G L G L G L'),
    ('kheṭakam', 'G L L L G L G G L G'),
    ('godhi', 'L L G L L G L'),
    ('mānākrāntā', 'G G G G G G G G G G G G G G G G G'),
    ('vāsavavanditā', ['G G G L L G L G L G', 'G G L L G L G L G']),
    ('vaṁśastham', 'L G L G G L L G L G L G'),
    ('bhujagaśiśubhṛtā', 'L L L L L L G G G'),
    ('panthā', 'L G G G G G'),
    ('amarandi', 'G G L G L L G L'),
    ('parīvāhaḥ', 'L L L G G L G G L G G L G G'),
    ('mālāvalayam', 'G G G G L L L L G G L L L L G G'),
    ('aviralaratikā', 'G L L L L L L G L G L G'),
    ('vīrā', 'G G G G L L L L G'),
    ('kaḍāram', 'L G G L L L L G G G G'),
    ('troṭakam', 'L L L L G L G L G G L L G L L G'),
    ('adhikārī', 'L L G G L L G'),
    ('ayamānam', 'L L G L L G L L G L L G L L G L L G L L G G'),
    ('satī', 'L L L G'),
    ('atulapulakam', 'L L L L L L L L L L L L L L L L L L L L L L L G'),
    ('mattākrīḍam', 'G G G G G G G G L L L L L L L L L L L L L L G'),
    ('sāravarohā', 'G L L G G L L L L G G L L L L G'),
    ('kaucamāraḥ', 'L L G G G L G G'),
    ('samudrakāntā', ['G G L L G L G L G G', 'G G G L L G L G L G G']),
    ('bhīmābhogaḥ', 'G G G G G L G G L G G G G G G G L G G L G G'),
    ('tanumadhyā', 'G G L L G G'),
    ('kalasvanavaṁśaḥ', 'G L L G L L G G L L G'),
    ('kalasvanavaṁśaḥ', [' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ']),
    ('vidhunidhuvanam', 'G G G L L L L L L G G L L L L G G G G'),
    ('kūlam', 'G G L L L G G G G G'),
    ('madanamālā', 'L L L G L G L L L G G'),
    ('bhūridhāmā', 'L L G G L G G'),
    ('sāmikā', 'G L G G L G L'),
    ('śrutakīrttiḥ', 'L L L L G G G L L G G'),
    ('sūriṇī', 'G L G G G'),
    ('kāmalā', 'L L L L L L G G G L G G L G'),
    ('mitasakthi', 'L L L L L G L L G L G L L G L'),
    ('pātaśīlā', ['L L G L L L G G G L G G', 'G G L G G G G L G G']),
    ('vargavatī', ['G L L G L L G L L G G', 'L L G L L G L L G G']),
    ('lakṣaṇalīlā', 'G L L G G L G G G G G'),
    ('karañji', 'L G L L L L G L'),
    ('viśvaviśvāsaḥ', 'G G G L G G L G G L G G G L G G G G G G L G G L G G'),
    ('bhujaṅgaḥ', 'L G G L G G L G G L G G L G G L G G L G G L G G'),
    ('nandaḥ', 'G L G G'),
    ('lalanā', 'G L L G G G L L G L L G'),
    ('bahulayā', 'G L G L L L G'),
    ('dhamanikā', 'L L G L G L L L L G'),
    ('bhārāvatāraḥ', 'L L L G G L L G L L L L L L L G G L G G'),
    ('vārayātrikam', 'G L L G L G G L G L G'),
    ('paragatiḥ', 'G L G L L L L L G L L L G'),
    ('vidhāritā', 'L G L L G L L G L G L G'),
    ('sudhādharā', 'G L G L G L G G L G L G L G'),
    ('dārikā', 'L L G L G L L L G L G'),
    ('asitadhārā', 'L L G L L L L L G G'),
    ('sundarī', ['L L G L L G L G L G', 'L L G G L L G L G L G']),
    ('bhāṣā', 'L G G G L G L L'),
    ('saṅkalpāsāraḥ', 'G G G G G G G G G G G G G G'),
    ('vindhyārūḍham', 'G G G G L G G G G G G L G G'),
    ('holā', 'L L L G G G G'),
    ('śiśiraśikhā', ['L L L L L L G L G L G', 'L L L L G L L G L G L G']),
    ('śākhoṭaki', 'L L L G G G L L'),
    ('bhasalavinoditā', 'L G L G L L L L L G L G'),
    ('niskā', 'G G G L L G'),
    ('abhīrukā', 'L G L G L L L L L L L L G'),
    ('apayodhā', 'L L G G L G G G G G G'),
    ('prabhāsitā', ['L L G L L G L G L G', 'G G G L L G L G L G']),
    ('sarāvikā', 'L G L G L G L G L G'),
    ('saraghā', 'L L G G G L L G'),
    ('kuhū', 'L G L L G L L G L'),
    ('viṣamavyālī', 'L L L L L G G G G G G G'),
    ('viṣamavyālī', [' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ']),
    ('sragdharā', 'G G G G L G G L L L L L L G G L G G L G G'),
    ('candrahāsakarā', 'G L G L L G L G L L G L G'),
    ('indhā', 'G G L G L L'),
    ('lāsyalīlālayaḥ', ['G G L L G G G L G G L G G', 'G L L L L G G G L G G L G G']),
    ('adhīrā', 'G L L G G G G'),
    ('jaloddhatagatiḥ', 'L G L L L G L G L L L G'),
    ('dhīradhvānam', 'G G G G G G G G G L L G G G'),
    ('mālinī', 'L L L L L L G G G L G G L G G'),
    ('arbhakapaṅktiḥ', ['L L G G L L G L G L G G', 'G L L G L L G L G L G G']),
    ('anūpakam', ['L L L L G L L G L G L G', 'L L G L L G L G L G']),
    ('kusumavicitrā', 'L L L L G G L L L L G G'),
    ('kiśalayam', 'L L L G G G L'),
    ('kumudinīvikāśaḥ', 'L G L G G L L L G L G G'),
    ('svidā', 'L G L L L L G'),
    ('vāsakalīlā', 'G L L G G G L L G G G L L G G G L L G G G G'),
    ('uditam', 'L L G L L G L L G G'),
    ('sthālī', 'G G L G L G'),
    ('vāsaramaṇikā', 'G L L L L G L L G G L L'),
    ('bhūrivasu', 'L G G G L L L'),
    ('madanalalitā', 'G G G G L L L L L G G G L L L G'),
    ('asambādhā', 'G G G G G L L L L L L G G G'),
    ('madalekhā', 'G G G L L G G'),
    ('vaṁśalonnatā', 'G L G L G L G L G G G G G G G L G L G L G G G G'),
    ('yugadhāri', 'L L G L G G G G'),
    ('śalkaśakalam', 'G L L L G L L G L L G'),
    ('hāsikā', 'G G G L G'),
    ('mantharāyanam', 'L L L G L G L L L L L L G L L G L L G L L G G'),
    ('nārācikā', 'G G L G L G L G'),
    ('cakoraḥ', 'G L L G L L G L L G L L G L L G L L G L L G L'),
    ('masṛṇam', 'L L L L L L G G L'),
    ('sindhuk', 'G G L L L L L L'),
    ('elā', 'L L G L G L L L L L L L L G G'),
    ('prapātalikā', 'G L L L L G L G L G L L G'),
    ('rasadhārā', 'L L L L G G L L L L G G G'),
    ('ulapohā', ['G L L G L L G L G L G G', 'L L G G L L G L G L G G']),
    ('nirvindhyā', 'L G L L L G G G G'),
    ('puṣpitāgrā', ['L L L L L L G L G L G G', 'L L L L G L L G L G L G G']),
    ('upohā', 'L G G L G L L'),
    ('ari', 'G L L L L L L G'),
    ('pākali', 'L L L G L G L L'),
    ('marmasphuram', 'G G L G L L L G L G G L G'),
    ('sarasīkam', ['G G L G L L L G L L G G', 'L L G G L L L G L L G G']),
    ('ādhidaivī', 'L G G G G G L G G L G G'),
    ('vīranīrājanā', 'L G G L G G L G G L G G G L G G L G G L G G'),
    ('adhīrakarīram', 'G G G L L L L L L G L L L L G L L L L G L L G G'),
    ('haṁsamālā', 'G L G G L G G'),
    ('sṛtamadhu', 'L L G G L L L L'),
    ('savyālī', 'G G G G G G G G G G G G G'),
    ('mārābhisaraṇam', 'G G L L L L G G G G L L L L G L G G G'),
    ('nirmuktamālā', 'G G G G L G G L L L L L L G'),
    ('akṣarāvalī', 'G L G L L G L G L G'),
    ('pañcaśākhī', 'L L L L L G L G L G G'),
    ('kumudamālā', 'L L L G G L L L G G L L L G G L L L G G L L L G G'),
    ('rasabhūma', 'L L G L G L L L G L'),
    ('upodgatā', ['L L G G L L G L G L G G', 'L L G L L G L G L G G']),
    ('avoḍhā', 'G G G G L G'),
    ('avoḍhā', [' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ']),
    ('somarājī', 'L G G L G G'),
    ('gūrṇikā', 'G L G G G L L'),
    ('paṅkavatī', 'G L L L L L L G L L G L L'),
    ('manmathaḥ', 'L L G L L G G L L G L L G G'),
    ('saudāmanadāma', 'L L G L L G L L G L L G L L L L G L L G G L L G L'),
    ('madhumārakam', 'L L G L G L'),
    ('caṇḍī', 'L L L L L L L L G L L G G'),
    ('kharviṇī', 'G L G G G G L'),
    ('bhujaṅgoddhatam', 'G G L G L L G L G G L G L L G G L G L L L G'),
    ('ārādhinī', 'G G L G G G G G G G G'),
    ('kanakamālikā', 'G L G L L L G L G L L L G L G L L L G L G'),
    ('ruciram', 'G L L L L G G'),
    ('arti', 'L G G L L L'),
    ('nameruḥ', 'G G L L G L G L G G'),
    ('nīlaśārdūlam', 'L L L L L L G G G L G G L G G L G G'),
    ('kalāpāntaritā', 'L G G L L G L G G G'),
    ('aupagavam', ['L L L G L G G L G L G', 'G L L G L G G L G L G']),
    ('virataprabhā', 'G L L G L L L L L G L G'),
    ('vīravaṭu', 'L L L G L L L'),
    ('kūlacāriṇī', 'G L G L G L G G G G G'),
    ('mattagajendraḥ', 'G L L G L L G L L G L L G L L G L L G L L G G'),
    ('vidyunmālā', 'G G G G G G G G'),
    ('pravahlikā', 'G L L L G L G L G'),
    ('śraddharā', 'G L G L G L L G'),
    ('sphoṭakṛīḍam', 'L L L L G G G G G G G G G G G'),
    ('mañjumālatī', 'G L G L G L L L G L G L G'),
    ('komalakalpakalikā', 'L L G L G G L L G L L L G'),
    ('lalāmalalitādharā', 'L G L G L G L G L G L G'),
    ('amandapādaḥ', 'G L L L L G L G L G G'),
    ('udayanamukhī', 'L L L L L G L L L L L G'),
    ('viśvapramā', ['G G L G G L G G L G', 'L G L G G L G G L G']),
    ('madanakam', 'L L L L L L L L G'),
    ('upagataśikhā', 'L L L L L G L G L L G L G'),
    ('kuṭhārikā', 'L G L G G L G'),
    ('avarodhavanitā', ['L L L G L L G L L G L G L G', 'L L G L L G L G L G L L L G G']),
    ('viśvamukhī', 'G L L G L L G L L G'),
    ('upasthitā', 'G G L L G L L G L G G'),
    ('śunakam', 'G L L G L G'),
    ('parabhānu', 'L G G L L G L'),
    ('vihāvā', 'L G G L G G L G'),
    ('virāmavāṭikā', 'L L L L G L G L G L L G L L L L G L G L G L L L L G'),
    ('upasaṁkulā', 'L L G L G L G G L G'),
    ('kanakitā', 'G L L G L L L L L L L L G'),
    ('upasarasīkam', ['L L G G L L L G L L G G', 'G G L G L L L G L L G G']),
    ('jāsari', 'G L L L G L L'),
    ('nūtanam', 'G L G L L L G L L G L L G L G'),
    ('upodgatā', ['L L G L L G L G L G G', 'L L G G L L G L G L G G']),
    ('bhadrā', ['G G L G G L L G L G G', 'L G L G G L L G L G G']),
    ('strī', 'G G'),
    ('pathyā', 'L L G L G L L L G L G G L G'),
    ('sūrasūcakaḥ', 'G G G L L G L G L L L G L L G L L G L G G L G G L G'),
    ('apavāhaḥ', 'G G G L L L L L L L L L L L L L L L L L L L L G G G'),
    ('apavāhaḥ', [' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ']),
    ('sāvaṭu', 'L G L G L L'),
    ('kāntāram', 'L G G G G G L L L L L G G L G G L'),
    ('prapañcacāmaram', 'L L L L L L G L G L G L G L G L G L G'),
    ('tomaram', 'L L G L G L L G L'),
    ('kalādhāmam', 'G L L G L L L G L G G G G'),
    ('kṛtamālam', 'G G L L G L L G G G L L G G'),
    ('dharā', 'G G L G'),
    ('upalinī', 'L L L G L G L G'),
    ('caturīhā', 'L G L G L L G G'),
    ('saramāsaraṇiḥ', 'L L G L L G G G L G G L G G'),
    ('chāyā', 'L G G G G G L L L L L G G G L G G L G'),
    ('rasikarasālā', 'L L L L L L L L G L L G G L L G G L L L L L L G G'),
    ('jvalitā', 'L L G L L L L L L L L G'),
    ('kroḍāntikam', 'G G L G L L L'),
    ('virohi', 'L G L L L G L'),
    ('parimitavijayā', 'L L L L L L G L G L G G'),
    ('avarodhavanitā', ['L L G L L G L G L G L L L G G', 'L L L G L L G L L G L G L G']),
    ('vṛntam', 'L L G G G G L L'),
    ('hīrāṅgī', 'G G G L L L L G G G'),
    ('vipannakadanam', 'L L L G L G L L L G G G G'),
    ('sāndrapadam', 'G L L G G L L L L G L'),
    ('vanavāsinī', 'L L G L L G L G L G L L G L G L L L L L G L'),
    ('pikālī', 'G L G L G G'),
    ('vāmavadanā', 'G L L L G L G G L G G L G'),
    ('vikasitapadmāvalī', 'L L L L G G L G G G G'),
    ('vinatākṣī', 'L L G G L L L L L L L L G'),
    ('yuddhavirāṭ', ['G G G L L G L G L G G', 'G G L L G L G L G G']),
    ('dṛtiḥ', 'L L L L L G G'),
    ('kiṁśukāvalī', ['G G G L L L L G L G L G G', 'G G L L G L G L G G']),
    ('sairavī', 'G L G G G G G'),
    ('saṁlakṣyalīlā', 'L L L G L G L L L G L G L L L G G L G G'),
    ('kūrcalalitam', 'G L G G L G G L G G L L L G'),
    ('anṛju', 'G L L L'),
    ('madirā', 'G L L G L L G L L G L L G L L G L L G L L G'),
    ('śikhilikhitā', 'G G G L L L L G'),
    ('saralāṅghri', 'G G L L L G L'),
    ('līlālekhaḥ', 'G G G G G G G G G G G G G G G'),
    ('śakuntakuntalaḥ', 'G G G G L G G L G L L L L L L G L G L G L G L G L G'),
    ('krīḍā', 'L G G G'),
    ('vātuli', 'L G G L G G L L'),
    ('kumāralīlā', 'G G G L L L L L L G L G L G G'),
    ('vāsavilāsavatī', 'G L L G L L G L L G G G G'),
    ('rūpāvaliḥ', 'G G L L L L L L L L L G'),
    ('kṣamāpāli', 'L G L G G L'),
    ('prajñāmūlam', 'G G G G L L L L L L G G G'),
    ('surahitā', ['L L L L L L L L G L L G G', 'G G L L L L L L L L L L G']),
    ('gahanā', 'G L L L L L G L L G'),
    ('bhekālokaḥ', 'G L L G G G G G G G G L L L L L L G G G'),
    ('vellitavelam', 'G L L G L L G L L G G G L L G L L L L L L L L G'),
    ('ambudāvalī', 'L L G L G G L L G L G L G'),
    ('luptā', ['L L G G L L G L L G L G', 'L L G L L G L L G L G']),
    ('vilambanīyā', 'L L L G L L L L G L G L G G'),
    ('kuśalakalāvatikā', 'G G G L L L L G L L G'),
    ('siṁhalekhā', 'G L G L G L G G'),
    ('kelicaram', 'L L L L G G L L L L L'),
    ('mṛgendramukham', 'L L L L G L L G L G L G G'),
    ('vīraviśrāmaḥ', 'L L L L L L G L G L L L G L G G G'),
    ('haṁsarutam', 'G G G L L L G G'),
    ('madāvadātā', 'L L G G L L G L G L G L G G'),
    ('sampākaḥ', 'G G G G G L L'),
    ('vīravikrāntaḥ', 'G G G L L L L G L G G L G G L G G L G G L G G L G G'),
    ('lakṣmī', 'G L G G L G G L'),
    ('nandanam', 'L L L L G L G L L L G L G L G G L G'),
    ('kuhakakuharam', 'L L L L L L G G G L G G L L L L L L G G G L G G L G'),
    ('vāravatī', 'L L G G L L G L L G'),
    ('ārbhavam', 'G L G L G L'),
    ('līlālolaḥ', 'G G G G L L L L G G G G G'),
    ('vaśamūlam', 'L L G G L L L L G L G L G G'),
    ('vayasyaḥ', 'L G G G L G G'),
    ('kharpari', 'L G L G G L L'),
    ('sambodhā', 'L G L G G L L L L L L G G G'),
    ('tāmarasam', 'L L L L G L L G L L G G'),
    ('rucirā', 'L G L G L L L L G L G L G'),
    ('pañjari', 'G L L G G G L L'),
    ('vilulitamañjarī', 'L L L L G L G G G G G'),
    ('arthaśikhā', 'G L L L L L L G L L G'),
    ('lodhraśikhā', 'G G G L L G L L G L L G G'),
    ('kiñjalki', 'G G L G L'),
    ('pataṅgapādaḥ', 'L G L G G L G G L G G L G G L G G L'),
    ('jāriṇī', ['L L L G G L G G L G', 'G L G G L G L L L G G L G']),
    ('viśambhari', 'L L L L L L L G G L L L L L'),
    ('akhaniḥ', 'L L L L G L L G'),
    ('jālapādaḥ', 'G G L G G G G L G G G'),
    ('kāṇḍamukhī', 'L G L G L L G L L G'),
    ('indraphalā', 'G L L G G G G G'),
    ('kalanāvatī', ['L L G L G L L L G L G L G', 'L L G L G L L L G L L G G']),
    ('kañjā', 'L G L G G G'),
    ('vṛddhavāmā', 'G G L G G L L G L G G L G'),
    ('bhārṅgī', 'L G L L L G G G'),
    ('kuradi', 'L G L L L L L'),
    ('īḍā', 'G G L L L L L G'),
    ('śroṇī', 'L G L G G G L'),
    ('paṭupaṭṭikā', 'L L G L G L L G L G G'),
    ('maśagā', 'L G G L L G'),
    ('vedhāḥ', 'G G L L G G G'),
    ('meghālokaḥ', 'L G G G G G G G G'),
    ('anucāyitā', 'L L L L L G L G L G'),
    ('pratisīrā', 'G G G G L L G G'),
    ('sutalam', 'L L G G L G L L G G L G'),
    ('harṣiṇī', 'G L G G L L L'),
    ('vaisārī', ['G G L L G L G L G', 'G G G L L G L G L G']),
    ('apramāthinī', ['L L G G L L G L G L G G', 'L L L L G L L G L G L G G']),
    ('puṭamardi', 'L L L L G L'),
    ('samayaprahitā', 'L L G L L G L G G L G G'),
    ('viśālāntikam', 'G G L G G L G G L G'),
    ('śṛkhalavalayitam', 'G L L L L L L L L G L L G G G L L L L L L L G L L G'),
    ('parimalalalitam', 'L L L L L L G G L G G'),
    ('mandari', 'G L L'),
    ('kamalaśikhā', 'L L L L G G G G G G L L L L G L L G L L G'),
    ('sthūlā', 'G G L L L G G'),
    ('ahilā', 'G G L L L G L G L G'),
    ('prabhā', 'L L L L L L G L G G L G'),
    ('upasthitam', 'L G L L L G G G L G G'),
    ('śarabhūriṇī', 'G L G L L G L G L L G L G L L G L G L L G L G G G'),
    ('vaisāruḥ', 'G G L L L G G G G'),
    ('pratari', 'G L G L L L'),
    ('vārttāhārī', 'L L L L G L L G G G G'),
    ('nābhasam', 'L G L L G L L L G L G'),
    ('vīrāntā', 'L G L L L G G G G G'),
    ('kumbhakam', 'L L L L L L G L G G L G G L G G L G G L G G L G G L'),
    ('nimagnakīlā', 'L G L G G L L G L G G L'),
    ('vāri', 'L G G L'),
    ('saubhagakalā', 'G L L L G L L L G L G'),
    ('haṁsī', ['L G L G G L L G L G G', 'G G L G G L L G L G G']),
    ('śeṣāpīḍam', 'G G G G L L L L G L L'),
    ('viplutaśikhā', 'G L L L G L G L G G L G'),
    ('sudhā', ['G G G L L G L G L G', 'L L G G L L G L G L G']),
    ('ābhāsamānam', 'L G G L G G L G G L G G G G L G G L G G L G G L G G'),
    ('mallapallīprakāśam', 'L G G L G G L G G L G G L G G L G G L G G L G G L'),
    ('hīnatālī', ['L L G G L L L L G L G L G L G G', 'G G G L L L L G L G L G']),
    ('karadhā', ['G G G L L G L G L G', 'L L L L L L G L G L G']),
    ('vipākavatī', 'L L L G L L L G L L G L L G'),
    ('varkaritā', 'G G G G L L G'),
    ('gītikā', 'L L G L G L L G L G L L G L G L L G L G'),
    ('visasi', 'L L G L L L'),
    ('baddhā', ['G G G G L L L L L L G', 'L L G L L G L L L L L L G']),
    ('āśāpādaḥ', 'G G G G L L L L G L G'),
    ('suvadanā', 'G G G G L G G L L L L L L G G G L L L G'),
    ('kuśakam', 'G L G L L L L L'),
    ('ujjvalā', 'L L L L L L G L L G L G'),
    ('kāmākṣī', ['L L G L L G L L L L L L G', 'G G G G L L L L L L G']),
    ('acalanayanam', 'L L L L L L L L L L L L L L L L L'),
    ('pravādapadā', 'L L G L G L G L L G'),
    ('bhramaravilasitā', 'G G G G L L L L L L G'),
    ('ākhyānakī', ['G G L G G L L G L G G', 'L G L G G L L G L G G']),
    ('manthānakam', 'G G L G G L'),
    ('bhujalatā', 'L L L L L G G G L L G'),
    ('mayūkhasaraṇiḥ', 'G L L L L G L G L L L G G'),
    ('unnarma', 'G L L G L L L L G L L G G L'),
    ('kālavarma', 'L L L G L L L G L G L'),
    ('phaladharam', 'L L L L L L G L L G'),
    ('suri', 'L L L L G G G'),
    ('svāgatā', 'G L G L L L G L L G G'),
    ('bhāsitabharaṇam', 'G L L L L G G G G G G G'),
    ('bhasalaśalākā', 'G G G G L L L L G G G G L L L L G G G G L L L L G G'),
    ('krūrāśanam', 'G G L L L L G G L L L L L L G G G'),
    ('pāṭalikā', ['L L L L G G L L L L G G', 'G L L G L L G L L G G']),
    ('vaśaṁvadaḥ', 'L L G L L G L L G L L G L L G L L G L L G L L G L L'),
    ('bhadravirāṭ', ['G G L L G L G L G G', 'G G G L L G L G L G G']),
    ('nimnāśayā', 'G G L G G G G'),
    ('vilambitamadhyā', 'G G G L L G L L G G G'),
    ('acaṭu', 'L L L L L L L'),
    ('kṛtakavali', 'L L L L L L L L L L'),
    ('dorlīlā', 'L L G L L G L G G G G G'),
    ('kāmaśālā', 'G L G G L G G L G G L G G L'),
    ('valgā', 'G G L G G L G G L'),
    ('kaṁsari', 'G G G G L L'),
    ('madākrāntā', ['L L G L L G L G L G L G G', 'G G G L L G L G L G L G G G']),
    ('sarasī', 'L L L L G L G L L L G L L G L L G L G L G'),
    ('pūrṇā', 'G G L L G L G'),
    ('bhāratī', 'G G G G G G G G G G G'),
    ('mṛgendu', 'L G L'),
    ('sarojāvālī', 'L G G L G G G L G G L G'),
    ('sukhaśailam', 'G G G G L L G G L L G G'),
    ('kumāralalitā', 'L G L L L G G'),
    ('kamanī', 'L L G L G G'),
    ('anantadāmā', 'L L L L L L L L G L G L G G'),
    ('kilikitā', ['G L G L L L G L G L G', 'L L L G L L L G L G L G']),
    ('varajāpi', 'G L L L L G L'),
    ('tanvī', 'G L L G G L L L L L L G G L L G L L L L L L G G'),
    ('gajagatiḥ', 'L L L G L L L G'),
    ('vireki', 'G L G L L L G L G L'),
    ('sāhūti', 'G G G G G L'),
    ('pariṇāhī', 'G G G G L L L L G G L L G G'),
    ('vidhuravitānam', 'L L L L L L G L L L L G G'),
    ('gaṅgodakam', 'G L G G L G G L G G L G G L G G L G G L G G L G'),
    ('korakitā', ['G L L G L L G L L G G', 'L L L L G G L L L L G G']),
    ('indraḥ', 'L G L L G L L G G G'),
    ('upadhānam', 'L G L L L L L G L L G G'),
    ('pāñcālāṅghriḥ', 'L L L L G G G G'),
    ('bhujaṅgajuṣī', 'G L G L L G G L G L L G'),
    ('citibhṛtam', 'L L L L L L L G L G'),
    ('maṇimālā', 'G G L L G G G G L L G G'),
    ('viyogavatī', 'L G L L G L L L L L L G'),
    ('indravadanā', 'G L L L G L L L G L L L G G'),
    ('lulitam', 'L L G L L G L L G L'),
    ('māṇavakam', 'G L L G G L L G'),
    ('upāḍhyam', ['G L L G L L G L G L G G', 'L L L L L G L G L G G']),
    ('niśipālam', 'G L L L G L L L G L L L G L G'),
    ('viṣvagvitānam', 'G G L G L L L G L L L L G G L G G L G G'),
    ('viṣvagvitānam', [' L L G L G L L L G L ', ' L L L L L G L G L G ', ' G L G L L L G L L G ', ' L L G L G L L L G L G L G ']),
    ('śraddharāntā', 'G L G G L G G L G G L G G'),
    ('hemahāsaḥ', 'G L G G L G G L G G'),
    ('aupagavītam', ['G L L G L G G L G L G', 'L L L G L G G L G L G']),
    ('amanā', 'L L G L L G L L'),
    ('pulakāñcitam', 'G L L L L G L L L L G G L L L L L L G L L G G'),
    ('vīvadhaḥ', 'L L L L G L L L G L G'),
    ('ulkābhāsaḥ', 'G G G G G L L L G G G G G'),
    ('kirātaḥ', 'L L L L G L G G L G G L G'),
    ('amānikā', 'L G L G L G G L'),
    ('dadhi', 'G L L G L L G L L'),
    ('gaṇadehā', 'L L G G G G L L G G'),
    ('vainasam', 'G L G L G'),
    ('alālāpi', 'L L G L G G L'),
    ('prasarā', 'G G G L L G L L G G'),
    ('bhūriśobhā', 'G G G G G G L L L L L L G G L G G L G G'),
    ('vabhrūḥ', 'G G L G G G'),
    ('kumbhāri', 'G G G G L'),
    ('arjitaphalikā', 'G L L L L G G L G L L G'),
    ('samāhitam', 'L L L L G L L G L L G L L G L L G L L G L L G G'),
    ('parabhṛtam', 'L L L G G L G'),
    ('pārthivam', 'L G L L L G L G L L L G L L L G L G'),
    ('visraṁsi', 'L L L L L G G G L L'),
    ('visraṁsi', [' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ']),
    ('hemarūpam', 'G L G G L G L G'),
    ('jaladarasitā', 'L L L L L G L G G L G G L G'),
    ('mālatikā', 'L G L L G L'),
    ('antarvikāsavāsakaḥ', 'G G L G L G L G L G L G'),
    ('phalinī', 'L L L L G G G L L G'),
    ('vasupadamañjarī', 'L L L L G L G L L L G L L G L G L G'),
    ('praharṣiṇī', 'G G G L L L L G L G L G G'),
    ('candralekhā', 'G G G G L L L L L L G G L G G L G G'),
    ('vāṭikāvikāśaḥ', 'G L L L L L L G G L G L G G'),
    ('madanayā', 'L L L L L L G G L L G'),
    ('karabhoddhatā', ['G L L G G L G L G L G', 'L L G L L L G L G L G']),
    ('vikalavakulavallī', 'L L L L L L G G L G G L'),
    ('mālādharaḥ', 'L L L L L G L G L L L G L G G L G'),
    ('kāṁsīkam', 'G G G L L L L G G'),
    ('upacitram', 'L L G L L G L L G L G'),
    ('subhadrikā', 'L L L L L L G L G L G'),
    ('vitānitā', 'L L L L L L L L L G L G L G'),
    ('kāmanibhā', 'G G G L L G G G L L'),
    ('indravajrā', 'G G L G G L L G L G G'),
    ('kuḍaṅgikā', 'L G L G L G L G L G L G L G'),
    ('toṭakam', 'L L G L L G L L G L L G'),
    ('paṇavaḥ', 'G G G L L L L G L G'),
    ('anukūlā', 'G L L G G L L L L G G'),
    ('vijohā', 'G L G G L G'),
    ('krīḍāyatanam', 'L L G L L G L L G G G L L G'),
    ('prapannapānīyam', 'G G L L G G G G L G L G G G'),
    ('ālepanam', ['L L L G G L G G L G G L G', 'L L L G L L L G G L G G L G']),
    ('dhṛtahālā', 'G G G G L L G G G'),
    ('parivṛḍham', 'L L L G G L G G L G G L G'),
    ('dhīrāvarttaḥ', ['G G G G G L L G G L L G G', 'G G G G L L L L G G G G G']),
    ('grāvāstaraṇam', 'G G G G L L L L G G L L G G G G L L G'),
    ('upameyā', ['L G L G G L L G L G L G', 'G G L G G L L G L G L G']),
    ('kṛṣṇagatikā', 'G L L L G L G G'),
    ('rādhikā', 'L L G G L L G L L G L G'),
    ('śiśubharaṇam', 'L L L L L L L L L L L L L L G G'),
    ('cārugatiḥ', 'L L L L L L L L G G G G L L L L G L G L G L G L G G'),
    ('kāmacāri', 'G G L G L L G L G L'),
    ('kanakaketakī', 'G G L L L G L G L L G L G'),
    ('sarasamukhī', 'G G L L L L L L G L'),
    ('salekhā', 'L L L L L L G G G L L L L L L G G'),
    ('bhadrakam', 'G L L G L G L L L L L G L L L G L G L L L G'),
    ('devalam', 'G G G L G G L'),
    ('vivaravilasitam', 'G G L L L L L L G G G G'),
    ('līlācandram', 'G G G G G G G G L L G G L L G'),
    ('līlācandram', [' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ']),
    ('kaṭhināsthi', 'G L L L L L L G L'),
    ('añcalavatī', 'G L L L G L L G L G L L L G'),
    ('ahatiḥ', 'L G G L L L L'),
    ('vātyā', 'G L L L G G G G'),
    ('aśokapuṣpam', 'L L L L L L G L G L G L G'),
    ('krośapadā', 'G L L G G G L L G G L L L L L L L L L L L L L L G'),
    ('padmāvatī', ['G G L G L L L G L L G G', 'L L G L G L L L G L L G G']),
    ('vaṁśāropī', 'L G G G L L G G G G'),
    ('vidyādhāraḥ', 'G G G G G G G G G G G G'),
    ('nāsābharaṇam', 'G G L L G G G L L G G L L G'),
    ('halodgatā', 'L L L L G L G L G'),
    ('uddhatikarī', 'G L L L G G G G G G G'),
    ('hetiḥ', 'L L L L G L L G L G L L G L'),
    ('karṇasphoṭam', 'L L L L G G G G L L L L G G G G L'),
    ('bhaurikam', 'G L G G L G G L G'),
    ('kokapadam', 'G L L G G G L L G G L L L L L L L L L L L L G G'),
    ('sahajā', 'L L G L L G L G L G'),
    ('lalitāgamanam', 'L L G L L G L G G G G'),
    ('kalpadhāri', 'G L G G L G G L G L G L G L G L'),
    ('kāmarūpam', 'G G G G L G G L L L L L G G L G G'),
    ('celāñcalam', 'G G L G L L L L G L G L G G'),
    ('gambhāri', 'G L G G L G G L G G L'),
    ('gambhāri', [' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ']),
    ('viśadacchāyaḥ', 'L L G G G L L G G G'),
    ('kalki', 'G L G L L'),
    ('kaṇikā', 'G G L L G'),
    ('amati', 'G L L L L L'),
    ('cañcarīkāvalī', 'L G G G G G G L G G L G G'),
    ('hrīḥ', 'G L G G L'),
    ('arditam', 'G L L G L L G L L G L L G L L G L L L L L L G G'),
    ('kalpamukhī', 'G L L G G L G'),
    ('drutalambinī', 'L L G L L G L G L L G L G'),
    ('bimbam', 'L L L L L G L G G'),
    ('bimbam', [' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ']),
    ('lasadasu', 'L L L L L G L G'),
    ('vyāhāri', 'G L L G G G L'),
    ('dhīrāvarttaḥ', ['G G G G L L L L G G G G G', 'G G G G G L L G G L L G G']),
    ('kalāpatiprabhā', 'G L G L G L G L G L G L G'),
    ('camūrubhīruḥ', ['G L G L L L L G L G L G', 'L L G L L L L G L G L G G']),
    ('suṣamā', 'G G L L G G G L L G'),
    ('hrīṇahaiyaṅgavīnam', 'G L G G L G G L G G L G G L G G L G G L G G L G G'),
    ('aḍamaruḥ', 'L L L L L L L L L L L L L'),
    ('kulādhārī', 'L G G G L G G G'),
    ('aparājitā', 'L L L L L L G L G L L G L G'),
    ('keram', 'G L G G L L G L L G'),
    ('mauktikadāma', 'L G L L G L L G L L G L'),
    ('mahonmukhī', 'G G G L G L G'),
    ('saṁhatikā', 'L L G L G L L G L G'),
    ('asudhārā', 'L G L G L G G L G L G G'),
    ('vinayavilāsaḥ', 'L L L L G G L L L L G G L L L L G G L L L L G G G G'),
    ('subhadrāvataraṇiḥ', 'G G G G G L G G L L L G'),
    ('akoṣakṛṣṭā', ['L L G G L L G L G L G L G G', 'G G L L G L G L G G']),
    ('ayamitam', 'L L L G L L'),
    ('sārasanāvaliḥ', 'L L L G L L L G L L G L G'),
    ('śantanu', 'G L L G G L L'),
    ('kārpikā', 'G L G L G L L'),
    ('amālīnam', 'L G G L G G G G G G G'),
    ('sumohitā', 'L G L G G G G'),
    ('cittacintāmaṇiḥ', 'G L G G L G G L G L L L L G L G G L G G L G G L G'),
    ('vāntabhāraḥ', 'L L L G G L G G'),
    ('paddhari', 'L G G G G L L'),
    ('arilā', 'L L G G L L G L L G L L'),
    ('mattebhavikrīḍitam', 'L L G G L L G L G L L L G G G L G G L G'),
    ('mattālī', 'G G G G G L L G G G G G'),
    ('amatiḥ', 'G G G L L L L'),
    ('kāmukalekhā', 'G L L G G G L L G G L'),
    ('mṛṣṭapādā', 'G L G G G L G'),
    ('piculam', 'L L G L L G L G L G L'),
    ('abhikhyā', 'L L G G G G'),
    ('bhūrighaṭakam', 'G G G L L L G G G G G'),
    ('rathoddhatā', 'G L G L L L G L G L G'),
    ('śaṅkāvalī', 'G G L G L L G L G L L L L L G'),
    ('kāsāram', 'G G G G G G G G L L L L G G L L G'),
    ('vāṇīvāṇaḥ', 'G G G G L L L L G G L L G G L L G G G G'),
    ('kumāragatiḥ', 'L G L L L L G L L L L G'),
    ('paricāravatī', 'G G L G L L G L L G'),
    ('vāhāntaritam', 'G G L L L L G L L G L L L L L L G'),
    ('sūtaśikhā', 'G G L L G G L L G G L L L L G G'),
    ('āpaṇikā', 'L G L G G L L G L L G L G'),
    ('vallavīvilāsaḥ', 'G L G L G G L G G G G'),
    ('kulyāvarttam', 'G G G G G G L L G G L L G G L L'),
    ('manthari', 'G G G L G G L L'),
    ('madanoddhurā', 'G L L G L L G L G'),
    ('bhadrikā', 'G L G L L L G L G'),
    ('jhillīlīlā', 'L L L L G G G G G G G G L G L G G G G'),
    ('paraprīṇitā', ['L L L L L L G G L G G L G', 'L L L L L L L L G G G L G G L G']),
    ('paurasari', 'G L L G L L L'),
    ('śārdūlalalitam', 'G G G L L G L G L L L G G G L L L G'),
    ('kalpamīlitā', 'G L G G L G G L G G L G L G'),
    ('amoghamālikā', 'L G L G L G L G G G G'),
    ('nīpavanīyakam', 'G L L L L L L L L L L G G L L L L G L L G L L G G'),
    ('saṅgamavatī', 'G L L L G L L L L L L G'),
    ('abhidhātrī', 'L L G L L G L L G L G L G L G G'),
    ('alparutam', ['G L L L L L L G L L G L L', 'G L L L L L L G G L L L L']),
    ('alparutam', [' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ']),
    ('tanimā', 'L L L L L L L L G G'),
    ('śobhā', 'L G G G G G L L L L L L G G L G G L G G'),
    ('valīkendu', 'L L G G L G G L'),
    ('aśaniḥ', 'L L L L L L G G L L L L L'),
    ('mahanīyā', 'L G G L L G G'),
    ('kalanāyikā', 'L G L G G L L L L L G L G'),
    ('upodari', 'L G L L G L L'),
    ('mālavikā', 'G G L L G L L L G L G'),
    ('bodhāturā', 'L G G G G G L G G G'),
    ('mudiram', 'L L G L L G L L G L L G L L G L L G L L G L L G G'),
    ('paṭu', 'L L L L'),
    ('vidyadālī', 'L G G L G G L G G L G G L G G L G G L G G'),
    ('saurabhi', 'G L L L L G'),
    ('vegavatī', ['L L G L L G L L G G', 'G L L G L L G L L G G']),
    ('rudrālī', 'L L L L L G G G'),
    ('daṇḍī', 'G G L L L L G G L L L L G G L L L G'),
    ('keśavatī', 'L G G G L L G'),
    ('āsavavāsitā', ['L L L G L L L G L G L G L G G', 'L L G G L L G L G L G L L L G G']),
    ('krośitakuśalā', 'G L L L L G L L G G G'),
    ('kīṭamālā', 'L L G L G L G G L'),
    ('vindu', 'L G G G G L'),
    ('vindu', [' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ']),
    ('anirayā', ['L L L G L L L L G L G L G', 'L L L G L L L G L L G L G']),
    ('anāmayam', 'L G L L G L L G L L G L L G L L G L L G L L G L'),
    ('kāntā', ['G G G L L G L G L G G', 'G G L L G L G L G G']),
    ('nirmedhā', 'L L L G G L G G G G'),
    ('surasā', 'G G G G L G G L L L L L L G G L L L G'),
    ('kāmā', 'G G L L L L L G G'),
    ('kāladhvānam', 'G G G G G G L L L L G G G G'),
    ('valvajam', 'G L L G L L G G L L L L L L G G G'),
    ('alipadam', ['G L G G L G L L L G G L G', 'L L L G G L G G L G']),
    ('nālī', 'L G G G G'),
    ('pāñcāli', 'G G L'),
    ('upāḍhyam', ['L L L L L G L G L G G', 'G L L G L L G L G L G G']),
    ('varatrā', 'G L L L G L L G L L G G'),
    ('varatrā', [' L L G L G L L L G L ', ' L L L L L G L G L G ', ' L L L L L L L L G L L G ', ' L L G L G L L L G L G L G ']),
    ('valīmukhī', 'L G L G L G'),
    ('valīmukhī', [' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ']),
    ('avanijā', 'L G L L G L G L G'),
    ('ākhrṭam', 'G L G L G L L L'),
    ('damanakam', 'L L L L L L L L L L G'),
    ('samayavatī', ['G G L L L L G G L L G', 'L L G G G G L L L L G']),
    ('akhaṇḍamaṇḍanam', 'L G L G L G G L G L G L G'),
    ('vyākośakośalam', 'G G L G L L L G G G L L L L G L L G L L G L G L G'),
    ('vyākośakośalam', [' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' L G L G G L L G L G G ']),
    ('khaṭakā', 'L G L L G L L G L L G'),
    ('harit', 'L L L L L G G L'),
    ('ghaṭikā', ['G G L L L G L G L G', 'L L G L L G L G L G']),
    ('viralam', 'G L L L L G G L L G'),
    ('śritakamalā', 'G L L G L L L L G G G'),
    ('śravaṇābharaṇam', 'L L L L G L L G L L G L L G L L G L L G L L G'),
    ('kalahakaram', 'L L L L L L L L L L L L G L L G'),
    ('vāsavavāsinī', ['L L L L G L G L L L G L L G L G', 'G G L L G L G L L L G L L G L G']),
    ('ratirekha', 'G G L L G G G L L G L L G G'),
    ('vimalā', 'L L G L L G L G L G G'),
    ('staradhi', 'L G L G L L L'),
    ('chalitakam', 'L L L G G L G L L G'),
    ('anālepanam', ['L L L G L L L G G L G G L G', 'L L L G G L G G L G G L G']),
    ('lāsyalīlā', ['G L L L L G G G L G G L G G', 'G G L L G G G L G G L G G']),
    ('atikali', 'G G L L L L'),
    ('taḍidambaram', 'G L L G L L G L L G L L G L L G L L G L L'),
    ('ārabhaṭī', 'G L L G L L L L L L G L L G G G'),
    ('maulimālikā', 'G L G L G G G G'),
    ('dhāri', 'G L G L'),
    ('viśālāmbhojālī', 'G G L L L G L G G G G G'),
    ('karaśayā', 'L L L G L L G L G'),
    ('citram', 'G L G L G L G L G L G L G L G L'),
    ('udāttahāsaḥ', 'L G L G G L G L L L G L G'),
    ('siktamaṇimālā', 'G L L L G G G G L L G G'),
    ('vikacavatī', 'L L L L G G G L L'),
    ('undari', 'G L L L G L G'),
    ('vibhā', 'L L L L G G G G L L G G G'),
    ('talpakatallajam', 'G L L G L L G L L G L L G L L L G L G G G'),
    ('nandi', 'G L L G L L'),
    ('dāmaghaṭitā', 'L L L L L L G L L L G'),
    ('babhrulakṣmīḥ', 'G L G G L G G G L G G L G G'),
    ('amarāvatī', ['G L G L G L G L G L G L', 'L G L G L G L G L G L G G']),
    ('amarāvatī', [' L L G L G L L L G L ', ' L L L L L G L G L G ', ' G L L L L L L G L L G ', ' L L G L G L L L G L G L G ']),
    ('guñjā', 'G G L L G G L'),
    ('kṣut', 'G L L L L'),
    ('śivikā', 'G L L G L L G L L G L L G L L G L L G L L G L L G'),
    ('lumbākṣī', 'L L G L L G L L L G G G'),
    ('maṇihaṁsaḥ', 'L L G L G L L G L G L L G L G'),
    ('mārdaṅgī', ['G G G L L L L G L L L L L L L L G G', 'L L G L L L L L G L L L G G']),
    ('rambhā', 'G G L L L L G G G'),
    ('bhujaṅgaprayātam', 'L G G L G G L G G L G G'),
    ('prahāṇaḥ', 'L G G G G G G'),
    ('rasadhāri', 'L L G L G G G'),
    ('rasadhāri', [' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ']),
    ('mattā', 'G G G G L L L L G G'),
    ('kiraṇakīrttiḥ', 'G G L L G L G G L G L L L L L L L G G'),
    ('rasikaparicitā', 'L L G G G L L L L L L G'),
    ('niryatpārāvāraḥ', 'G G G G G L G G L G G L G G'),
    ('saṁbhṛtaśaradhiḥ', 'G L L L L L L G G G L L L L L L G G L L G G L'),
    ('hoḍapadā', 'G L L G L G G'),
    ('bhīmārjanam', 'G G L G L G G'),
    ('śāyinī', 'L L L L L G L G L G L L L G L G G'),
    ('mauralikam', 'G L L G L L G'),
    ('lāsyakārī', 'G L G G L G G L G G L G G L G'),
    ('bhāvinīvilasitam', 'G L G L L L G L G L L L G L G L L L G L G L L L G'),
    ('varddhiṣṇu', 'G G L G G G L'),
    ('mayūrasāriṇī', 'G L G L G L G L G G'),
    ('valā', 'G L L G'),
    ('sarojavanikā', 'L G L L L G L G L G G'),
    ('meghadhvanipūraḥ', 'G G L L G G G G G G G'),
    ('viśeṣakabalitam', 'L L L L L L G G G G G G L G L L G L L G L L L L G'),
    ('dhanadhari', 'L L G L L L L'),
    ('siṁhapuccham', 'L G G L G G L G G L G G L G G'),
    ('haravanitā', 'L L L L L L L L L L L L G'),
    ('dārudehā', 'G L G G L G G L G G G'),
    ('īhā', ['L L L L G L L G L L G G', 'G L L G L L G L L G G']),
    ('pramodaḥ', 'L L L L L L G L G G L G G'),
    ('vāsinī', ['G G L L G L G L L L G L L G L G', 'L L L L G L G L L L G L L G L G']),
    ('moṭanakam', 'G G L L G L L G L L G'),
    ('pramitākṣarā', 'L L G L G L L L G L L G'),
    ('paritoṣā', 'L L G L L L L G L L G G'),
    ('nirudam', 'L L G L L L L L'),
    ('atailam', ['L G L G G L G G L G', 'G G L G G L G G L G']),
    ('arpitamadanā', 'G L L L L G L L L L G G'),
    ('vanitāvilokaḥ', 'G G L G G L L L G L G G'),
    ('sārddhapadā', 'G L G L G G L L G L G L G'),
    ('dīpakam', 'G L L G G L L L L G G L L G G'),
    ('guṇavatī', 'L L L G G G'),
    ('rucimukhī', ['L L L L L L L L G L L G G', 'L L L L L L G L L L L G G']),
    ('sulūḥ', 'L L L L G'),
    ('mañjīrā', 'G G G G G G G L L G G G L L G G G G'),
    ('vidrumadolā', 'L L L L G G G G L L G G'),
    ('mānavatī', 'L G L L G L L G L L G L L G L L G L L G L L G'),
    ('vimāninī', ['L L G G L L G L G L G', 'G G G L L L L G L G L G']),
    ('paridhānīyam', 'L L L L L L G L L G G L L G L L G G L L G G G'),
    ('muhurā', 'L L G L G L L'),
    ('śarameyā', 'L L G G L L L G L L G G'),
    ('mahī', 'L G'),
    ('pramālikā', ['L L G G L L G L G L G G', 'L L G L L G L G L G G']),
    ('praguṇam', 'L L G G G'),
    ('praguṇam', [' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ']),
    ('śaśikalā', 'L L L L L L L L L L L L L L G'),
    ('līlāratnam', 'G G G G G G L L G G G G'),
    ('gahvaram', 'G L G G L G G L G L G'),
    ('abhrabramaṇam', 'G G L L L L G G G L L G L L L L L L L L L L L L G'),
    ('priyaṁvadaḥ', 'L L L G L L L G L G L G'),
    ('snu', 'ल'),
    ('vilulitavanamālā', 'L L L L L L G G G L L L L L L G G G'),
    ('parviṇī', 'L L L L L L G L G L L L G L G G L G'),
    ('atiraṁhaḥ', 'L G L L G L L G L G L G G'),
    ('atiraṁhaḥ', [' G G G L L G L G L G L L G G ', ' L L G L L L L G L G L G G ', ' L L L L L L L L G ', ' L L L L L L L L L L G L L G G ']),
    ('vīṇādaṇḍam', 'L G L L L G L G G G G G'),
    ('lolalolambalīlam', 'G L G G L G G L G G L G G L G G L G G'),
    ('svaravarṣiṇī', 'L L G L G L L G L G G G'),
    ('svanakarī', 'L L L G L L G'),
    ('ravonmukhī', 'G G L L G L G L G'),
    ('śāntasurabhiḥ', 'G L L L L L G L G L L G L L G'),
    ('suvṛttiḥ', 'L L G L L L L L L G G'),
    ('naragā', 'L L L L G G L L G G'),
    ('upendravajrā', 'L G L G G L L G L G G'),
    ('virājikarā', 'L G L L G G G G'),
    ('virājikarā', [' L G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ', ' G G L G G L L G L G G ']),
    ('cārvaṭakam', 'G G G G L L G L L G G G G G G'),
    ('murajikā', 'L L L G G L L'),
    ('saṁsṛtaśobhāsāraḥ', 'L L G G G L L G G G G'),
    ('nāndīmukhī', 'L L L L L L G G L G G L G G'),
    ('aśvagatiḥ', 'G L L G L L G L L G L L G L L L L G'),
    ('vṛttahāri', 'L G G L G L'),
    ('viratimahatī', 'G G L L L L L L L L G G'),
    ('īhāmṛgī', 'G G L G L L G G L G G'),
    ('nīrāñjaliḥ', 'G G L L L L G G L G'),
    ('hīrakahāradharam', 'G L L G L L G L L G L L G L L G L L'),
    ('nirasikā', 'L L L G L G'),
    ('sphuṭaghaṭitā', 'L L L L G G L L L'),
    ('mālīnam', 'G G G L L'),
    ('kāru', 'L L G L'),
    ('priyajīvitam', 'G L L G L L G L L G L L G L L G L L G L L G L L G G'),
    ('pañcaśikhā', 'L L G L L G G G'),
    ('uditavijohā', 'G G L G G L L L L G G'),
    ('sammadākrāntā', ['G G G L L G L G L G L G G G', 'L L G L L G L G L G L G G']),
    ('dodhakam', 'G L L G L L G L L G G'),
    ('dhṛṣṭapadam', 'G L L G L L L G L L G G'),
    ('kurucarī', 'G L G G L L L G'),
    ('śephālī', 'L G G G G G G G G G'),
    ('anibhṛtam', 'L L L G G L'),
    ('chalitakapadam', 'G G L L L L L G L L G G'),
    ('vakrāvalokaḥ', 'L L L L L L G G G G L G G L G G'),
    ('sambuddhiḥ', 'L L G G G L L G G'),
    ('śampā', 'G G L L L L G G G G G G'),
    ('anirbhāraḥ', 'L G G G G G G G'),
    ('vahirvali', 'L G L L G L G'),
    ('śambhuḥ', 'L L G G G L L G G G L L G G G G G G G'),
    ('svinnaśarīram', 'G L L G G L G G L G G L G'),
    ('bhūrimadhu', 'G G G G L L L'),
    ('nirgalitamekhalā', 'L L L L L L G L G L L L G L L L G L G'),
    ('hāriṇī', 'G G G G L L L L L L G G L G G L G'),
    ('abhirāmā', 'L L G G L L G G L L L L G'),
    ('śaragītiḥ', 'G L G L L G G'),
    ('śrīḥ', 'गु'),
    ('mātrā', 'G G G L L L L L L G G'),
    ('bhogāvalī', 'G G L G L L G L G L L G L L L L L L L G L G'),
    ('vasantamālikā', ['L L G L L G L G L G G', 'L L G G L L G L G L G G']),
    ('jihmāśayā', 'G G L G L L L G L L G'),
    ('rājarājī', 'G G L G G L G'),
    ('kanakakāminī', 'L G L G G L L L G L G'),
    ('mayūvadanā', 'G L L L G L L G L G L L G L G'),
    ('śikhariṇī', 'L G G G G G L L L L L G G L L L G'),
    ('ānaddham', 'G L G L L L L L G G G L G G G'),
    ('mahoddhatā', 'L G G L G L G'),
    ('madhuvāri', ['L L G L G L L L G L G L G', 'G G L G L L G L G L L G L']),
    ('sukhakārikā', 'L L G L G L L G L G G G L'),
    ('kāmoddhatā', 'G G L G G L L'),
    ('kilikitā', ['L L L G L L L G L G L G', 'G L G L L L G L G L G']),
    ('mṛdukīlā', 'L L G G L G'),
    ('ramaṇaḥ', 'L L G'),
    ('kareṇuḥ', 'G L G G G G'),
    ('camūruḥ', ['L L G L L L L G L G L G G', 'G L G L L L L G L G L G']),
    ('khagatiḥ', 'G L L G L L G L L G L L G L L G'),
    ('bhogāvaliḥ', 'G G L L L L L L L L G G L L G G'),
    ('candrikā', 'L L L L L L G G L G G L G'),
    ('nārācam', 'L L L L L L G L G G L G G L G G L G'),
    ('śilīmukhojjṛmbhitam', 'G G G L L G L G L L L L L G L G G L G'),
    ('kanyā', 'G G G G'),
    ('vasumatī', 'G G L L L G'),
    ('kalitakamalavilāsaḥ', 'L L L L L L G G G G G'),
    ('nīrāntikam', 'G G L G L L L G L L G G'),
    ('sārikā', ['G L G L L L G L G L G', 'G L G L L L G L L G G']),
    ('manolā', 'L G G L L G G G'),
    ('lalitalalāma', 'L L L L G L G G L G G L G G L G G L L L G'),
    ('vijayaparicayā', 'L L L L L L G G L L G G'),
    ('mṛdumālatī', ['L L L L G L L G L G L G', 'L L L L L L G L G L G']),
    ('mandākṣamandaram', 'L L L L L L G G G G G G L G L G L G G G G'),
    ('parikhāyatanam', 'L L G L L G L L G G L L L L G G'),
    ('śarat', 'L L L G L L G L L G'),
    ('yaśaskarī', 'L G L G L G G G'),
    ('viśikhalatā', 'L L L L G L G L G G L G'),
    ('surāḍhyā', ['L L L L L L G L G L G G', 'G G G L L G L G L G G']),
    ('bhāskaram', 'G L L L L L L G L L G G G L L L L L L L L L L G G'),
    ('nīhārī', 'G G G G G G L'),
    ('rāḍhi', 'G L L G G L'),
    ('ālolaghaṭikā', ['L L G L L G L G L G', 'G G L L L G L G L G']),
    ('kalā', 'L G L G'),
    ('lavalīlatā', 'G L L G L G L L L G L L G'),
    ('kāraviṇī', 'G L L L G L G L L L G L L G'),
    ('hīram', 'G G L L L L G'),
    ('bimbālakṣyam', 'G G G G L G G G L G G L G G'),
    ('pārāvāraḥ', 'G G L L L L L L L L G G G G'),
    ('praphullakadalī', 'L G L L L G G G G G G'),
    ('ayavatī', ['L L G G G G L L L L G', 'G G L L L L G G L L G']),
    ('mīnapadī', 'G L L G L G L'),
    ('surayānavatī', 'L L G L L G G L L G'),
    ('kumbhodhnī', 'G G G G L L L G L L G G'),
    ('muśaki', 'G G L L L L L'),
    ('bhūmadhārī', 'L G G L G G G G'),
    ('bhūmadhārī', [' G G L G G L L G L G G ', ' L G L G G L L G L G G ', ' L G L G G L L G L G G ', ' G G L G G L L G L G G ']),
    ('vāṇībhūṣā', 'G G G G G G G G L L L L G G G'),
    ('virodhinī', 'L L L G L L L L G L G L G'),
    ('bhujaṅgabhṛtā', ['L L G L L G L L G L L G G', 'G L L G L L G L L G L L G']),
    ('śambaradhārī', 'G L L G G L L G G'),
    ('camarīcaram', 'L L L L L L G L G L L L G L G'),
    ('vihāriṇī', 'L L G L G L G G L G G'),
    ('māyāsārī', 'L L L L G G G G G'),
    ('pramodapadam', ['L L L L G L L G L G L L L G G', 'L L L L L L G L G L G L G G']),
    ('sudāyi', 'L G L L L L'),
    ('kiṁśukāstaraṇam', 'G L G L L G L G G G G G'),
    ('phalguḥ', 'L L G G L L L L G G L L L L G G L'),
    ('pārāvataḥ', 'G G L G G L G G L G G L G'),
    ('atisurahitā', ['G G L L L L L L L L L L G', 'L L L L L L L L G L L G G']),
    ('sammadavadanā', 'G L L G L L G L L L L G'),
    ('viśālaprabham', 'L G L G G L G G L G'),
    ('vanitābharaṇam', 'G L L G L L L L G L L G'),
    ('malayasurabhiḥ', 'G G G L L L L L L G G G'),
    ('galitanālā', 'L G L G L L L G G G L G'),
    ('saurakāntā', 'G L G G L L G'),
    ('bhujaṅgavijṛmbhitam', 'G G G G G G G G L L L L L L L L L L G L G L L G L G'),
    ('akahari', 'L L L L L L L L L L L L L L'),
    ('ardhakṣāmā', 'G G G G G L L G G'),
    ('kāsārakrāntā', 'G G G G G L L G L L G G'),
    ('tārakam', 'L L G L L G L L G L L G G'),
    ('uditadineśaḥ', 'L L G L L L L G G G G'),
    ('pratāritā', 'L L G L L L G L G L G'),
    ('nardaṭakam', 'L L L L G L G L L L G L L G L L G'),
    ('lolam', 'G G L G G'),
    ('dṛptadehā', 'L G G G L G G G L G G L G G'),
    ('dhaunikam', 'G L L L L L L L G'),
    ('pratimā', 'L L G L L G L L G L L G L L G L L G L L G'),
    ('parāmodaḥ', 'L G G L L G L L G L G L L L L G G G'),
    ('dhoritam', 'G L L L L L G L G G L G L L G'),
    ('kharakarā', 'L L L G L G G'),
    ('garuḍarutam', 'L L L L G L G L L L G L G G L G'),
    ('karabhit', 'L L G L L G G'),
    ('sāriṇī', 'G L G L L L G L G L L L G L G'),
    ('acaladhṛtiḥ', 'L L L L L L L L L L L L L L L L'),
    ('sumukhī', 'L L L L G L L G L L G'),
    ('śukāvalī', ['G G L L G L G L G G', 'G G G L L L L G L G L G G']),
    ('ītiḥ', 'G L L L G G'),
    ('nibhālitā', 'L L G G G L G L G'),
    ('śarakalpā', 'L L L L L L L L G L L L L G G'),
    ('rathapadam', 'L L L L L L L L G G G'),
    ('kacchapī', 'L G G G L G'),
    ('bṛhaccharāvatī', ['L L G G L L L L L L G L G L G', 'L L L L L L G L G L G G']),
    ('padyā', 'L G L G G G G'),
    ('śārdūlavikrīḍitam', 'G G G L L G L G L L L G G G L G G L G'),
    ('priyatilakā', 'G L L G L L L L G'),
    ('sahelikā', 'L G L G L L G L G'),
    ('vilāsavāsaḥ', 'G L L L L G G L L G L L L L G L G L G L L G G'),
    ('mugdham', 'G G G L'),
    ('kaṇṭhī', 'L G L G G'),
    ('cāmaram', 'G L G L G L G'),
    ('kaṁsāsāri', 'L G G G G G L'),
    ('methikā', 'G L G L L G L'),
    ('paṅktiḥ', 'G L L G G'),
    ('hemamihikā', 'G L L L G L L G L G L L G L'),
    ('śuddhāntam', 'L L L L L L L L G G G G'),
    ('vilāsavāpī', ['G G L L G L G L G G', 'L L G G L L G L G L G L G G']),
    ('navanīlatā', ['L L G L L G L G L G', 'L L G G L L L G L G L G']),
    ('upalekhā', 'L L G G L L L L L G L G'),
    ('kālasāroddhataḥ', 'L G L G G L L G L L L G L G G L G'),
    ('carapadam', 'L L L G G L G G L G'),
    ('maṇimukhī', 'L L L G L G L'),
    ('śilā', 'L G L L G'),
    ('ṛṣabhagajavilasitam', 'G L L G L G L L L L L L L L L G'),
    ('ṛṣabhagajavilasitam', [' G G L G G L L G L G L G ', ' G G L G G L L G L G L G ', ' L G L G G L L G L G L G ', ' G G L G G L L G L G L G ']),
    ('sukhelā', 'L L G L G L G L G G'),
    ('añcitāgrā', ['L L L L G L L G L G L G G', 'L L L L L L G L G L G G']),
    ('virahavirahasyam', 'G G G L L L L L L G G L L G G L L L L L L L L G G'),
    ('meghavisphūrjitā', 'L G G G G G L L L L L G G L G G L G G'),
    ('kākiṇikā', 'L G L L G L G L L L G L L G'),
    ('hariṇaplutam', 'G G G L L G L G L L G L G L L G L G'),
    ('kandavinodaḥ', 'G L L G G G L L G G G'),
    ('māṇavikāvikāṣaḥ', 'G G L G L L G L L G L G G'),
    ('vasantatilakā', 'G G L G L L L G L L G L G G'),
    ('śarāvatī', ['L L L L L L G L G L G G', 'L L G G L L L L L L G L G L G']),
    ('krīḍitakaṭakā', 'G L L L L G L L G G G G G G G'),
    ('senikā', 'G L G L G L G L G L G'),
    ('surākṣī', 'L L L L G G L G G G'),
    ('kaṅkaṇakvāṇavāṇī', 'G G G G L G G L G G L G G L G G L G G L G G'),
    ('varmitā', 'G L G L G L L G L G'),
    ('śālinī', 'G G G G G L G G L G G'),
    ('viyadvāṇī', ['G G G L L G L G L G G G', 'L L G G L L G L G L G G']),
    ('kusumbhinī', 'L G L G L L L L G L G L G G'),
    ('baladhārī', 'L L G G L L L L G G'),
    ('pratīhāraḥ', 'G L G G L G G L G G L G G L G G L'),
    ('prapātaḥ', 'L G G L G G L G G L G G L G'),
    ('upahitacaṇḍī', 'L L G G L L L L G G G'),
    ('maṇimadhyam', 'G L L G G G L L G'),
    ('madhyādhārā', 'G G G G L L G G G G'),
    ('tūṇakam', 'G L G L G L G L G L G L G L G'),
    ('tanukilakiñcitam', 'G G G G G G G G G L L L L G L L L L G G L L G G G G'),
    ('acalaviratiḥ', 'L L L L L L L L L L L L L L L L L L L L L G'),
    ('vanitāvinodi', 'L L L G L L G L G L'),
    ('dhavalam', 'L L L L L L L L L L L L L L L L L L G'),
    ('paripoṣakam', 'L L G L L G L L G L L G L L G L L G'),
    ('nīlā', 'G G L L L L G L G L G'),
    ('khaurali', 'L L L L G G G G L L'),
    ]
