# -*- coding: utf-8 -*-
"""List of metres from Vrtta-ratnakara, input by Dr. Dhaval Patel."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

dhaval_vrtta_data_small = [
    ('śrī', 'G'),
    ('strī', 'GG'),
    ('nārī', 'GGG'),
    ('mṛgī', 'GLG'),
    ('kanyā', 'GGGG'),
    ('paṅkti', 'GLLGG'),
    ('tanumadhyā', 'GGLLGG'),
    ('śaśivadanā', 'LLLLGG'),
    ('vasumatī', 'GGLLLG'),
    ('madhumatī', 'LLLLLLG'),
    ('madalekhā', 'GGGLLGG'),
    ('kumāralalitā', 'LGLLLGG'),
    ('haṁsamālā', 'LLGGLGG'),
    ('vidyunmālā', 'GGGG — GGGG'),
    ('chitrapadā', 'GLLGLLGG'),
    ('māṇavaka', 'GLLGGLLG'),
    ('haṁsaruta', 'GGGLLLGG'),
    ('samānikā', 'GLGLGLGL'),
    ('pramāṇikā', 'LGLGLGLG'),
    ('campakamālā', 'GLLGGGLLGG'),
    ('nārācaka', 'GGLGLGLG'),
    ('halamukhī', 'GLGLLLLLG'),
    ('bhujagaśiśubhṛtā', 'LLLLLLG — GG'),
    ('śuddhavirāṭ', 'GGGLLGLGLG'),
    ('paṇava', 'GGGLL — LLGGG'),
    ('mayūrasāriṇī', 'GLGLGLGLGG'),
    ('rukmavatī', 'GLLGGGLLGG'),
    ('mattā', 'GGGG — LLLLGG'),
    ('manoramā', 'LLLGLGLGLG'),
    ('upasthitā', 'GG — LLGLLGLG'),
    ('indravajrā', 'GGLGGLLGLGG'),
    ('upendravajrā', 'LGLGGLLGLGG'),
    ('sāndrapada', 'GLLGGLLLLGG'),
    ('sumukhī', 'LLLLG — LLGLLG'),
    ('dodhaka', 'GLLGLLGLLGG'),
    ('śālinī', 'GGGG — GLGGLGG'),
    ('vātormī', 'GGGG — LLGGLGG'),
    ('bhramaravilasita', 'GGGG — LLLLLLG'),
    ('śrī', 'GLLGG — LLLLGG'),
    ('rathoddhatā', 'GLGLLLGLGLG'),
    ('svāgatā', 'GLGLLLGLLGG'),
    ('vṛntā', 'LLLL — LLLLGGG'),
    ('bhadrikā', 'LLLLLLGLGLG'),
    ('śyenikā', 'GLGLGLGLGLG'),
    ('upasthita', 'LGLLLGGGLGG'),
    ('śikhaṇḍita', 'LGLLLGGGLGG'),
    ('mauktikamālā', 'GLLGLLGGLLG'),
    ('candravartma', 'GLGLLLGLLLLG'),
    ('vaṁśastha', 'LGLGGLLGLGLG'),
    ('indravaṁśā', 'GGLGGLLGLGLG'),
    ('toṭaka', 'LLGLLGLLGLLG'),
    ('drutavilambita', 'LLLGLLGLLGLG'),
    ('puṭa', 'LLLLLLGGGLGG'),
    ('pramuditavadanā', 'LLLLLLGLGGLG'),
    ('mauktidadāma', 'LGLLGLLGLLGL'),
    ('kusumavicitrā', 'LLLLGG — LLLLGG'),
    ('jaloddhatagati', 'LGLLLGLGLLLG'),
    ('bhujaṅgaprayāta', 'LGGLGGLGGLGG'),
    ('sragviṇī', 'GLGGLGGLGGLG'),
    ('priyaṁvadā', 'LLLGLLLGLGLG'),
    ('maṇimālā', 'GGLLGGGGLLGG'),
    ('lalitā', 'GGLGLLLGLGLG'),
    ('pramitākṣarā', 'LLGLGLLLGLLG'),
    ('ujjvalā', 'LLLLLLGLLGLG'),
    ('vaiśvadevī', 'GGGGG — GLGGLGG'),
    ('jaladharamālā', 'GGGG — LLLLGGGG'),
    ('navamālinī', 'LLLL — GLGLLLGG'),
    ('prabhā', 'LLLLLLGLGGLG'),
    ('mālatī', 'LLLLGLLGLGLG'),
    ('pañcacāmara', 'LGLGLGLGLGLG'),
    ('tāmarasa', 'LLLLGLLGLLGG'),
    ('kṣamā', 'LLLLLLGGLGGLG'),
    ('praharṣiṇī', 'GGGLLLLGLGLGG'),
    ('rucirā', 'LGLGLLLLGLGLG'),
    ('mattamayūra', 'GGGG — GLLGGLLGG'),
    ('mañjubhāṣiṇī', 'LLGLGLLLGLGLG'),
    ('nandinī', 'LLGLGLLLGLLGG'),
    ('candrikā', 'LLLL — LLGGLGLGG'),
    ('asambādhā', 'GGGGG — LLLLLLGGG'),
    ('aparājitā', 'LLLLLLG — LGLLGLG'),
    ('praharaṇakalikā', 'LLLLLLG — LLLLLLG'),
    ('vasantatilakā', 'GGLGLLLGLLGLGG'),
    ('induvadanā', 'GLLLGLLLGLLLGG'),
    ('alolā', 'GGGLLGG — GGGLLGG'),
    ('śaśikalā', 'LLLLLLL — LLLLLLLG'),
    ('mālā', 'LLLLLL — LLLLLLLLG'),
    ('maṇiguṇanikara', 'LLLLLLLL — LLLLLLG'),
    ('malinī', 'LLLLLLGG — GLGGLGG'),
    ('prabhadraka', 'LLLLGLGLLLGLGLG'),
    ('elā', 'LLGLG — LLLLLLLLGG'),
    ('candralekhā', 'GGGGLGG — GGLGGLGG'),
    ('ṛṣabhagajavilasita', 'GLLGLG — LLLLLLLLLG'),
    ('vāṇinī', 'LLLLGLGLLLGLGLGG'),
    ('śikhariṇī', 'LGGGGG — LLLLLGGLLLG'),
    ('pṛthvī', 'LGLLLGLG — LLLGLGGLG'),
    ('vaṁśapatrapatita', 'GLLGLGLLLGLL — LLLLG'),
    ('hariṇī', 'LLLLLG — GGGG — LGLLGLG'),
    ('mandākrāntā', 'GGGG — LLLLLG — GLGGLGG'),
    ('narkuṭaka', 'LLLLGLGLLLGLLGLLG'),
    ('kokilaka', 'LLLLGLG — LLLGLL — GLLG'),
    ('kusumitalatāvellitā', 'GGGGG — LLLLLG — GLGGLGG'),
    ('meghavisphurjita', 'LGGGGG — LLLLLG — GLGGLGG'),
    ('śārdulavikrīḍita', 'GGGLLGLGLLLG — GGLGGLG'),
    ('suvadanā', 'GGGGLGG — LLLLLLG — GGLLLG'),
    ('vṛtta', 'GLGLGLGLGLGLGLGLGLGL'),
    ('sragdharā', 'GGGGLGG — LLLLLLG — GLGGLGG'),
    ('madraka', 'GLLGLGLLLG — LGLLLGLGLLLG'),
    ('aśvalalita', 'LLLLGLGLLLG — LGLLLGLGLLLG'),
    ('mattākrīḍa', 'GGGGGGGG — LLLLL — LLLLLLLLLG'),
    ('tanvī', 'GLLGG — LLLLLLG — GLLGLLLLLLGG'),
    ('krauñcapadā', 'GLLGG — GLLGGLLL — LLLLLLL —LLLLG'),
    ('bhujaṅgavijṛmbhita', 'GGGGGGGG — LLLLLLLLLLG —LGLLGLG'),
    ('apavāha', 'GGGLLLLLL — LLLLLL — LLLLLL — LLGGG'),
    ('caṇḍavṛṣṭiprayātadaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLG'),
    ('arṇadaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('arṇavadaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('vyāladaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('jīmūtadaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('līlākaradaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('uddāmadaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('śaṅkhadaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('samudradaṇḍaka', 'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('bhujaṅgadaṇḍaka',
     'LLLLLLGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLGGLG'),
    ('pracitakadaṇḍaka', 'LLLLLLLGGLGGLGGLGGLGGLGGLGG'),
    ('upacitrā', ['LLGLLGLLGLG', 'GLLGLLGLLGG']),
    ('drutamadhyā', ['GLLGLLGLLGG', 'LLLLGLLGLLGG']),
    ('vegavatī', ['LLGLLGLLGLLGG', 'GLLGLLGLLGG']),
    ('bhadravirāṭ', ['GGLLGLGLGG', 'GGGLLGLGLG']),
    ('ketumatī', ['LLGLGLLLGG', 'GLLGLGLLLGG']),
    ('ākhyānikī', ['GGLGGLLGLGG', 'LGLGGLLGLGG']),
    ('viparītākhyānikī', ['LGLGGLLGLGG', 'GGLGGLLGLGG']),
    ('hariṇaplutā', ['LLGLLGLLGLG', 'LLLGLLGLLGLG']),
    ('aparavaktra', ['LLLLLLGLGLG', 'LLLLGLLGLGLG']),
    ('puṣpitāgrā', ['LLLLLLGLGLGG', 'LLLLGLLGLGLGG']),
    ('yavātparāmatīya', ['GLGLGLGLGLGL', 'LGLGLGLGLGLG']),
    ('padacaturūrdhva', ['........',
                         '............',
                         '................',
                         '....................']),
    ('āpīḍa', ['LLLLLLGG',
               'LLLLLLLLLLGG',
               'LLLLLLLLLLLLLLGG',
               'LLLLLLLLLLLLLLLLLLGG']),
    ('kalikā', ['LLLLLLLLLLGG',
                'LLLLLLGG',
                'LLLLLLLLLLLLLGG',
                'LLLLLLLLLLLLLLLLLLGG']),
    ('lavalī', ['LLLLLLLLLLGG',
                'LLLLLLLLLLLLLLGG',
                'LLLLLLGG',
                'LLLLLLLLLLLLLLLLLLGG']),
    ('amṛtadhārā', ['LLLLLLLLLLGG',
                    'LLLLLLLLLLLLLLGG',
                    'LLLLLLLLLLLLLLLLLLGG',
                    'LLLLLLGG']),
    ('udgatā', ['LLGLGLLLGL',
                'LLLLLGLGLG',
                'GLLLLLLGLLG',
                'LLGLGLLLGLGLG']),
    ('saurabhaka', ['LLGLGLLLGL',
                    'LLLLLGLGLG',
                    'GLGLLLGLLG',
                    'LLGLGLLLGLGLG']),
    ('lalita', ['LLGLGLLLGL',
                'LLLLLGLGLG',
                'LLLLLLLLGLLG',
                'LLGLGLLLGLGLG']),
    ('upasthitapracupita', ['GGGLLGLGLGLLGG',
                            'LLGLLLLGLGLGG',
                            'LLLLLLLLG',
                            'LLLLLLLLLLGLLGG']),
    ('vardhamāna', ['GGGLLGLGLGLLGG',
                    'LLGLLLLGLGLGG',
                    'LLLLLGLLL',
                    'LLLLLLLLLLGLLGG']),
    ('śuddhavirāḍārṣabha', ['GGGLLGLGLGLLGG',
                            'LLGLLLLGLGLGG',
                            'GGLLGLGLG',
                            'LLLLLLLLLLGLLGG']),
    ]
